// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_39_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln286,
        phi_ln39_out,
        phi_ln39_out_ap_vld,
        trunc_ln39_2_cast_out,
        trunc_ln39_2_cast_out_ap_vld,
        placement_dynamic_dict_Opt2Tile_keys_address0,
        placement_dynamic_dict_Opt2Tile_keys_ce0,
        placement_dynamic_dict_Opt2Tile_keys_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] zext_ln286;
output  [6:0] phi_ln39_out;
output   phi_ln39_out_ap_vld;
output  [6:0] trunc_ln39_2_cast_out;
output   trunc_ln39_2_cast_out_ap_vld;
output  [6:0] placement_dynamic_dict_Opt2Tile_keys_address0;
output   placement_dynamic_dict_Opt2Tile_keys_ce0;
input  [7:0] placement_dynamic_dict_Opt2Tile_keys_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] phi_ln39_out;
reg phi_ln39_out_ap_vld;
reg[6:0] trunc_ln39_2_cast_out;
reg trunc_ln39_2_cast_out_ap_vld;
reg placement_dynamic_dict_Opt2Tile_keys_ce0;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] zext_ln286_cast_fu_97_p1;
reg   [7:0] zext_ln286_cast_reg_142;
reg   [6:0] phi_ln39_load_reg_147;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln39_fu_114_p2;
reg   [0:0] icmp_ln39_reg_153;
wire   [6:0] add_ln39_fu_120_p2;
reg   [6:0] add_ln39_reg_157;
reg   [0:0] ap_phi_mux_UnifiedRetVal_phi_fu_89_p4;
reg   [0:0] UnifiedRetVal_reg_85;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state4;
wire   [63:0] trunc_ln39_2_cast_fu_109_p1;
reg   [6:0] phi_ln39_fu_46;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln40_fu_126_p2;
reg   [0:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_89_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        UnifiedRetVal_reg_85 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        UnifiedRetVal_reg_85 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_ln39_fu_46 <= 7'd0;
    end else if (((icmp_ln40_fu_126_p2 == 1'd0) & (icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_ln39_fu_46 <= add_ln39_reg_157;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln39_reg_157 <= add_ln39_fu_120_p2;
        icmp_ln39_reg_153 <= icmp_ln39_fu_114_p2;
        phi_ln39_load_reg_147 <= phi_ln39_fu_46;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        zext_ln286_cast_reg_142[5 : 0] <= zext_ln286_cast_fu_97_p1[5 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_89_p4 = 1'd0;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_89_p4 = UnifiedRetVal_reg_85;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_89_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        phi_ln39_out = 7'd100;
    end else if (((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln39_out = phi_ln39_load_reg_147;
    end else begin
        phi_ln39_out = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        phi_ln39_out_ap_vld = 1'b1;
    end else begin
        phi_ln39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        placement_dynamic_dict_Opt2Tile_keys_ce0 = 1'b1;
    end else begin
        placement_dynamic_dict_Opt2Tile_keys_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln39_2_cast_out = 7'd100;
    end else if (((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln39_2_cast_out = phi_ln39_load_reg_147;
    end else begin
        trunc_ln39_2_cast_out = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        trunc_ln39_2_cast_out_ap_vld = 1'b1;
    end else begin
        trunc_ln39_2_cast_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln40_fu_126_p2 == 1'd0) & (icmp_ln39_reg_153 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln39_reg_153 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_fu_120_p2 = (phi_ln39_fu_46 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign icmp_ln39_fu_114_p2 = ((phi_ln39_fu_46 < 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_126_p2 = ((placement_dynamic_dict_Opt2Tile_keys_q0 == zext_ln286_cast_reg_142) ? 1'b1 : 1'b0);

assign placement_dynamic_dict_Opt2Tile_keys_address0 = trunc_ln39_2_cast_fu_109_p1;

assign trunc_ln39_2_cast_fu_109_p1 = phi_ln39_fu_46;

assign zext_ln286_cast_fu_97_p1 = zext_ln286;

always @ (posedge ap_clk) begin
    zext_ln286_cast_reg_142[7:6] <= 2'b00;
end

endmodule //runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_39_2
