#include <map>
#include <vector>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <string>
#include <cstring>
#include <chrono>
#include <iostream>
#include <fstream>
using namespace std;
using namespace chrono;

//////////////////////////////////////////// some common classes ////////////////////////////////////////////
class Tile{
    public:
        int ID;   
        int X;  
        int Y; 
        Tile(){};
        Tile(int id, int x, int y){
            ID = id;
            X = x;
            Y = y;
        }
        bool operator ==(const Tile& t)
        {
            return (this->ID == t.ID) && (this->X == t.X) && (this->Y == t.Y);
        }
};

class CGRA{
    public:
        int size;
        vector<Tile> Tiles;
        CGRA(){};
        CGRA(int size){
            size = size;
            int ID = 0;
            for(int i = 0; i < size; i++){
                for(int j = 0; j < size; j++){
                    Tiles.push_back(Tile(ID, j, i));
                    ID++;
                }
            }
        }
};

// the variable decorated by "static" will be automatically initialized to 0, 
// which avoids unnecessary initialization operation after converting to RTL by HLS.
// if decorated by "const", the variable can be synthesised to ROM by HLS.

/////////// placement recommendation and placement&routing module related variables and functions ///////////
static const int cgra_size = 4; // square
static const int maxPCs = 100;
static const int bypassOverlapPages = 8;
static bool heterogenous = false; // if true, only half Tiles can access memory
static string architecture;
static int totalNodes, numTiles, RecMII, ResMII;
static CGRA cgra(cgra_size);
static int xDiff_Limit = 1; // kingmesh
static int yDiff_Limit = 1;
static int IDX_pd, idx_pd, IDX_pd_modulo, IDX_pd_bypass;
static int xDiff_CurToPred1, yDiff_CurToPred1, xDiff_BypassSrcToTgt, yDiff_BypassSrcToTgt;
static string curOpt, predOpt1;
static Tile curTile, predTile1;
static string bypassOpt, bypassSrcOpt, bypassTgtOpt;
static int bypassOptIdx;
static Tile bypassSrcTile, bypassTgtTile;
static bool dependency_forward, dependency_backward;
static vector<string> predecessors;
static map<string, vector<string>> dependency_successor;
static map<string, vector<string>> dependency_predecessor;
static int DynamicPlacement_II;
static vector<Tile> curOptPotentialPlacement;
static int threshold;
static map<string, int> placement_done;
static map<string, int> placement_dynamic_dict_Opt2PC;
static map<string, Tile> placement_dynamic_dict_Opt2Tile;
static map<string, Tile> placement_static_Opt2Tile;
static vector<vector<Tile>> allocated_tiles_levels_dynamic;
static vector<Tile> allocated_tiles;
static vector<string> placement_static;
static string placement_dynamic[maxPCs][cgra_size*cgra_size]; 
static string placement_dynamic_bypass[bypassOverlapPages][maxPCs][cgra_size*cgra_size]; // The placement of bypassOpt can be overlapped with DFGNode
static int placement_dynamic_occupy[maxPCs][cgra_size*cgra_size];
static int placement_dynamic_bypass_occupy[maxPCs][cgra_size*cgra_size][16];
static vector<float> TimeRatio;
static float Stage1TotalTimeCsmptPercent = 0;
void PlacementDynamic_Record(Tile);
void Calculate_CurToPred_Distance();
bool CurToPred_Distance_Satisfy_Topology();
void DynamicPlacement_SrcTgtInit_BypassMode(string, string);
void Dependency_Update_BypassMode_SrcTgt();
void Update_BypassSrcInfo();
bool SrcToTgt_Distance_Satisfy_Topology_BypassMode();
int Bypass_XbarIn_Direction(int, int);
int Bypass_XbarOut_Direction(int, int);
bool BypassOptPlacement_Gen_Record();
bool bypassOptGen_and_Placement(string, string);
bool RoutingAvailability_CheckPredecessor_and_Placement();
void CurOptPotentialPlacement_List_PartialInherit_Gen();
void CurOptPotentialPlacement_List_PartialInherit_BypassLess_Gen();
bool dynamic_placement_routing();
void Reset(string, string);
int calculate_startII(string, string);
void record_mappingResults(string, string);
void record_TimeConsumptionRatio(string, string);
void compare_mappingResults_withPython();
vector<vector<Tile>> generate_allocated_tiles_levels_dynamic(vector<Tile>, map<int, vector<Tile>>, vector<float>);
void analyze_static_levels_distribution(string);

////////////////////// cofiguration generation module related variables and functions ///////////////////////
static const int LocalRegNum = 8;
static const int ComputeRegNum = 2;
static bool insufficientLocalReg = false;
static string opcode;
static string srcOpt, tgtOpt;
static Tile srcTile, tgtTile;
static int local_register_status[maxPCs][cgra_size*cgra_size][LocalRegNum];
static int compute_register_status[maxPCs][cgra_size*cgra_size][ComputeRegNum];
void opcode_generation(int);
int CrossbarInIdx_Generation_FromWhichLocalReg(int);
int CrossbarOutIdx_Generation_ToWhichLocalReg(int, int);
int CrossbarInIdx_Generation_FromWhichFuncUnitOutput();
int CrossbarOutIdx_Generation_ToWhichFuncUnitInput(int, int);
int CrossbarInIdx_Generation_FromWhichDirectionTile();
int CrossbarOutIdx_Generation_ToWhichRouteReg();
int CrossBar_Type1_ControlSignal_Generation(int, int);
void CrossBar_Type2_ControlSignal_Generation(int, int);
void CrossBar_Type3_ControlSignal_Generation(int, int);
void CrossBar_Type4_ControlSignal_Generation(int, int, int, int);
void CrossBar_Type5_ControlSignal_Generation(int, int, int, int);
void CrossBar_Type6_ControlSignal_Generation(int, int, int, int);
void CrossBar_Type8_ControlSignal_Generation(int, int);
void CrossBar_Type9_ControlSignal_Generation(int, int);
void crossbar_8bitsControlSignal_predecessors_generation(int);
void crossbar_8bitsControlSignal_successors_generation(int);
void configuration_generation();
 

//////////////////////////////////////////// some huge variables ////////////////////////////////////////////
Tile xy2Tile[4][4] = {{cgra.Tiles[0], cgra.Tiles[4], cgra.Tiles[8], cgra.Tiles[12]},
                        {cgra.Tiles[1], cgra.Tiles[5], cgra.Tiles[9], cgra.Tiles[13]},
                        {cgra.Tiles[2], cgra.Tiles[6], cgra.Tiles[10], cgra.Tiles[14]},
                        {cgra.Tiles[3], cgra.Tiles[7], cgra.Tiles[11], cgra.Tiles[15]}};

// heterogenous CGRA, half Tiles cannot access memory
static vector<Tile> noMemAccess_Tiles = {cgra.Tiles[1], cgra.Tiles[5], cgra.Tiles[9], cgra.Tiles[13], cgra.Tiles[3], cgra.Tiles[7], cgra.Tiles[11], cgra.Tiles[15]};

static map<string, vector<vector<int>>> bpsStride_architecture = {
    {"Diagonal", {{1, 1}, // x move 1, y move 1
                  {1, 0}, // x move 1, y remains unchange
                  {0, 1}}}, // x remains unchange, y move 1 
    {"Orthogonal", {{1, 0},{0, 1}}}
};

static vector<string> test_kernels = {
"atax", "cholesky", "doitgen", "bicg", "gemm", "gemver", 
"gesummv", "mvt", "symm", "syrk", "trmm", "syr2k", 
"atax_u", "cholesky_u", "doitgen_u", "gemm_u", "symm_u", "syrk_u"};

static map<string, vector<string>> test_shapes = {
    {"atax",{"16-S"}},
    {"cholesky",{"16-S"}},
    {"doitgen",{"16-S"}},
    {"bicg",{"16-S"}},
    {"gemm",{"16-S"}},
    {"gemver",{"16-S"}},
    {"gesummv",{"16-S"}},
    {"mvt",{"16-S"}},
    {"symm",{"16-S"}},
    {"syrk",{"16-S"}},
    {"trmm",{"16-S"}},
    {"syr2k",{"16-S"}},
    {"atax_u",{"16-S"}},
    {"cholesky_u",{"16-S"}},
    {"doitgen_u",{"16-S"}},
    {"gemm_u",{"16-S"}},
    {"symm_u",{"16-S"}},
    {"syrk_u",{"16-S"}},
};

static map<string, map<string, vector<float>>> eachLevelUsedNumTiles_static_kernels_architecture = {
    {"Diagonal",{{"atax", {6.0f, 0.0f, 1.0f, 7.0f}}, // {kernel, {Level0, Level1, Level2，total} used Tiles in static mapping results under 4x4 CGRA}
                 {"cholesky", {4.0f, 1.0f, 1.0f, 6.0f}},
                 {"doitgen", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"bicg", {6.0f, 2.0f, 1.0f, 9.0f}},
                 {"gemm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"gemver", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"gesummv", {6.0f, 2.0f, 1.0f, 9.0f}},
                 {"mvt", {5.0f, 0.0f, 1.0f, 6.0f}},
                 {"symm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"syrk", {5.0f, 2.0f, 1.0f, 8.0f}},
                 {"trmm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"syr2k", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"atax_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"cholesky_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"doitgen_u", {6.0f, 2.0f, 1.0f, 9.0f}},
                 {"gemm_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"symm_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"syrk_u", {6.0f, 2.0f, 1.0f, 9.0f}},                              
                 }},
    {"Orthogonal",{{"atax", {6.0f, 0.0f, 1.0f, 7.0f}}, // {kernel, {Level0, Level1, Level2，total} used Tiles in static mapping results under 4x4 CGRA}
                 {"cholesky", {4.0f, 1.0f, 1.0f, 6.0f}},
                 {"doitgen", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"bicg", {6.0f, 2.0f, 1.0f, 9.0f}},
                 {"gemm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"gemver", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"gesummv", {9.0f, 12.0f, 4.0f, 25.0f}},
                 {"mvt", {5.0f, 0.0f, 1.0f, 6.0f}},
                 {"symm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"syrk", {5.0f, 2.0f, 1.0f, 8.0f}},
                 {"trmm", {6.0f, 1.0f, 1.0f, 8.0f}},
                 {"syr2k", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"atax_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"cholesky_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"doitgen_u", {6.0f, 2.0f, 1.0f, 9.0f}},
                 {"gemm_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"symm_u", {6.0f, 3.0f, 1.0f, 10.0f}},
                 {"syrk_u", {6.0f, 2.0f, 1.0f, 9.0f}},                              
                 }},
};

static map<string, int> DFG_NodesCount_kernels = {
    {"atax",21},
    {"cholesky",13},
    {"doitgen",21},
    {"bicg",26},
    {"gemm",20},
    {"gemver",24},
    {"gesummv",27},
    {"mvt",17},
    {"symm",19},
    {"syrk",16},
    {"trmm",19},
    {"syr2k",26},
    {"atax_u",25},
    {"cholesky_u",18},
    {"doitgen_u",30},
    {"gemm_u",30},
    {"symm_u",29},
    {"syrk_u",22},
};

static map<string, int> DFG_Theoretical_RecMII_kernels = {
    {"atax",4},
    {"cholesky",4},
    {"doitgen",4},
    {"bicg",4},
    {"gemm",4},
    {"gemver",4},
    {"gesummv",4},
    {"mvt",4},
    {"symm",4},
    {"syrk",4},
    {"trmm",4},
    {"syr2k",4},
    {"atax_u",4},
    {"cholesky_u",4},
    {"doitgen_u",4},
    {"gemm_u",4},
    {"symm_u",4},
    {"syrk_u",4},  
};

static map<string, int> CGRA_NumTiles = {
    {"16-S", 16},
};

static map<string, int> static_max_levels_architecture = { // total levels of 4x4 CGRA in given topology
    {"Diagonal", 3},
    {"Orthogonal", 3},
};

static map<string, map<int, int>> placement_static_Tile2Level_architecture = { //Referenced CGRA static mapping results are under 5x5 CGRA
    {"Diagonal", {{6, 0}, // Tile 6,7,8,11,12,13,16,17,18 level 0
                  {7, 0},
                  {8, 0},
                  {11, 0},
                  {12, 0}, 
                  {13, 0},
                  {16, 0},
                  {17, 0},
                  {18, 0},
                  {1, 1}, // Tile 1,2,3,5,9,10,14,15,19,21,22,23 level 1
                  {2, 1},
                  {3, 1},
                  {5, 1},
                  {9, 1}, 
                  {10, 1},
                  {14, 1},
                  {15, 1},
                  {19, 1}, 
                  {21, 1},
                  {22, 1},
                  {23, 1},
                  {0, 2}, // Tile 0,4,20,24, level 2
                  {4, 2},
                  {20, 2},
                  {24, 2}}},
    {"Orthogonal", {{6, 0}, // Tile 6,7,8,11,12,13,16,17,18 level 0
                  {7, 0},
                  {8, 0},
                  {11, 0},
                  {12, 0}, 
                  {13, 0},
                  {16, 0},
                  {17, 0},
                  {18, 0},
                  {1, 1}, // Tile 1,2,3,5,9,10,14,15,19,21,22,23 level 1
                  {2, 1},
                  {3, 1},
                  {5, 1},
                  {9, 1}, 
                  {10, 1},
                  {14, 1},
                  {15, 1},
                  {19, 1}, 
                  {21, 1},
                  {22, 1},
                  {23, 1},
                  {0, 2}, // Tile 0,4,20,24, level 2
                  {4, 2},
                  {20, 2},
                  {24, 2}}},
};

static map<string, map<int, vector<Tile>>> topology_architecture = { // mapping on 4x4 CGRA
    {"Diagonal", {{0, {cgra.Tiles[1], cgra.Tiles[4], cgra.Tiles[5]}}, // {Tile.ID, {List of Tiles connected to this Tile under current topology}}
                  {1, {cgra.Tiles[0], cgra.Tiles[2], cgra.Tiles[4], cgra.Tiles[5], cgra.Tiles[6]}},
                  {2, {cgra.Tiles[1], cgra.Tiles[3], cgra.Tiles[5], cgra.Tiles[6], cgra.Tiles[7]}},
                  {3, {cgra.Tiles[2], cgra.Tiles[6], cgra.Tiles[7]}},
                  {4, {cgra.Tiles[0], cgra.Tiles[1], cgra.Tiles[5], cgra.Tiles[8], cgra.Tiles[9]}},
                  {5, {cgra.Tiles[0], cgra.Tiles[1], cgra.Tiles[2], cgra.Tiles[4], cgra.Tiles[6], cgra.Tiles[8], cgra.Tiles[9], cgra.Tiles[10]}},
                  {6, {cgra.Tiles[1], cgra.Tiles[2], cgra.Tiles[3], cgra.Tiles[5], cgra.Tiles[7], cgra.Tiles[9], cgra.Tiles[10], cgra.Tiles[11]}},
                  {7, {cgra.Tiles[2], cgra.Tiles[3], cgra.Tiles[6], cgra.Tiles[10], cgra.Tiles[11]}},
                  {8, {cgra.Tiles[4], cgra.Tiles[5], cgra.Tiles[9], cgra.Tiles[12], cgra.Tiles[13]}},
                  {9, {cgra.Tiles[4], cgra.Tiles[5], cgra.Tiles[6], cgra.Tiles[8], cgra.Tiles[10], cgra.Tiles[12], cgra.Tiles[13], cgra.Tiles[14]}},
                  {10, {cgra.Tiles[5], cgra.Tiles[6], cgra.Tiles[7], cgra.Tiles[9], cgra.Tiles[11], cgra.Tiles[13], cgra.Tiles[14], cgra.Tiles[15]}},
                  {11, {cgra.Tiles[6], cgra.Tiles[7], cgra.Tiles[10], cgra.Tiles[14], cgra.Tiles[15]}},
                  {12, {cgra.Tiles[8], cgra.Tiles[9], cgra.Tiles[13]}},
                  {13, {cgra.Tiles[8], cgra.Tiles[9], cgra.Tiles[10], cgra.Tiles[12], cgra.Tiles[14]}},
                  {14, {cgra.Tiles[9], cgra.Tiles[10], cgra.Tiles[11], cgra.Tiles[13], cgra.Tiles[15]}},
                  {15, {cgra.Tiles[10], cgra.Tiles[11], cgra.Tiles[14]}}}}, 
    {"Orthogonal", {{0, {cgra.Tiles[1], cgra.Tiles[4]}}, // {Tile.ID, {List of Tiles connected to this Tile under current topology}}
                  {1, {cgra.Tiles[0], cgra.Tiles[2], cgra.Tiles[5]}},
                  {2, {cgra.Tiles[1], cgra.Tiles[3], cgra.Tiles[6]}},
                  {3, {cgra.Tiles[2], cgra.Tiles[7]}},
                  {4, {cgra.Tiles[0], cgra.Tiles[5], cgra.Tiles[8]}},
                  {5, {cgra.Tiles[1], cgra.Tiles[4], cgra.Tiles[6], cgra.Tiles[9]}},
                  {6, {cgra.Tiles[2], cgra.Tiles[5], cgra.Tiles[7], cgra.Tiles[10]}},
                  {7, {cgra.Tiles[3], cgra.Tiles[6], cgra.Tiles[11]}},
                  {8, {cgra.Tiles[4], cgra.Tiles[9], cgra.Tiles[12]}},
                  {9, {cgra.Tiles[5], cgra.Tiles[8], cgra.Tiles[10], cgra.Tiles[13]}},
                  {10, {cgra.Tiles[6], cgra.Tiles[9], cgra.Tiles[11], cgra.Tiles[14]}},
                  {11, {cgra.Tiles[7], cgra.Tiles[10], cgra.Tiles[15]}},
                  {12, {cgra.Tiles[8], cgra.Tiles[13]}},
                  {13, {cgra.Tiles[9], cgra.Tiles[12], cgra.Tiles[14]}},
                  {14, {cgra.Tiles[10], cgra.Tiles[13], cgra.Tiles[15]}},
                  {15, {cgra.Tiles[11], cgra.Tiles[14]}}}},     
};

static map<string, vector<string>> placement_static_kernels = {
    {"atax",{"phi0",
    "add14",
    "icmp15",
    "br16",
    "call1",
    "load2",
    "load5",
    "load9",
    "getelementptr3",
    "load6",
    "load10",
    "load4",
    "getelementptr7",
    "load8",
    "mul11",
    "add12",
    "store13",
    }},



    {"cholesky",{"phi0",
    "add10",
    "icmp11",
    "br12",
    "call2",
    "load3",
    "load4",
    "getelementptr5",
    "load6",
    "load7",
    "mul8",
    "sub9",
    "phi1",
    }},



    {"doitgen",{"phi0",
    "add18",
    "icmp19",
    "br20",
    "call1",
    "load2",
    "load6",
    "load11",
    "load3",
    "load7",
    "getelementptr12",
    "load4",
    "load8",
    "load13",
    "load5",
    "getelementptr9",
    "load14",
    "load10",
    "mul15",
    "add16",
    "store17",
    }},



    {"bicg",{"phi0",
    "add23",
    "icmp24",
    "br25",
    "call1",
    "load2",
    "load5",
    "load7",
    "load14",
    "load17",
    "getelementptr3",
    "load6",
    "load8",
    "load15",
    "getelementptr18",
    "load4",
    "getelementptr9",
    "load19",
    "load10",
    "load16",
    "mul11",
    "mul20",
    "add12",
    "add21",
    "store13",
    "store22",
    }},



    {"gemm",{"phi0",
    "add17",
    "icmp18",
    "br19",
    "call1",
    "load2",
    "load7",
    "load12",
    "load3",
    "getelementptr8",
    "load13",
    "getelementptr4",
    "load9",
    "load14",
    "load5",
    "load10",
    "mul6",
    "mul11",
    "add15",
    "store16",
    }},



    {"gemver",{"phi0",
    "add21",
    "icmp22",
    "br23",
    "call1",
    "load2",
    "load6",
    "load8",
    "load13",
    "load15",
    "load3",
    "load7",
    "getelementptr9",
    "load14",
    "getelementptr16",
    "getelementptr4",
    "load10",
    "load17",
    "load5",
    "mul11",
    "mul18",
    "add12",
    "add19",
    "store20",
    }},



    {"gesummv",{"phi0",
    "add24",
    "icmp25",
    "br26",
    "call1",
    "load2",
    "load6",
    "load10",
    "load14",
    "load20",
    "load3",
    "getelementptr7",
    "load11",
    "load15",
    "load21",
    "getelementptr4",
    "load8",
    "getelementptr16",
    "load18",
    "load5",
    "load17",
    "mul9",
    "mul19",
    "add12",
    "add22",
    "store13",
    "store23",
    }},



    {"mvt",{"phi0",
    "add14",
    "icmp15",
    "br16",
    "call1",
    "load2",
    "load4",
    "load8",
    "load3",
    "getelementptr5",
    "getelementptr9",
    "load6",
    "load10",
    "load7",
    "mul11",
    "add12",
    "store13",
    }},



    {"symm",{"phi0",
    "add16",
    "icmp17",
    "br18",
    "call1",
    "load2",
    "load6",
    "load10",
    "getelementptr3",
    "load7",
    "getelementptr11",
    "load4",
    "load8",
    "load12",
    "load5",
    "load13",
    "mul9",
    "add14",
    "store15",
    }},



    {"syrk",{"phi0",
    "add13",
    "icmp14",
    "br15",
    "call1",
    "load2",
    "load8",
    "load3",
    "load9",
    "getelementptr4",
    "load10",
    "load5",
    "mul6",
    "mul7",
    "add11",
    "store12",
    }},



    {"trmm",{"phi0",
    "add16",
    "icmp17",
    "br18",
    "call1",
    "load2",
    "load7",
    "getelementptr3",
    "load8",
    "getelementptr11",
    "load4",
    "load9",
    "load12",
    "load5",
    "load13",
    "mul6",
    "mul10",
    "add14",
    "store15",
    }},



    {"syr2k",{"phi0",
    "add23",
    "icmp24",
    "br25",
    "call1",
    "load2",
    "load7",
    "load12",
    "load3",
    "load8",
    "load13",
    "getelementptr4",
    "getelementptr9",
    "load14",
    "load5",
    "load10",
    "load17",
    "load19",
    "shl6",
    "shl18",
    "mul11",
    "mul20",
    "add15",
    "store16",
    "add21",
    "store22",
    }},



    {"atax_u",{"phi0",
    "add14",
    "icmp23",
    "br24",
    "call1",
    "load2",
    "load5",
    "load9",
    "getelementptr3",
    "load6",
    "load10",
    "getelementptr15",
    "load19",
    "load4",
    "getelementptr7",
    "load16",
    "getelementptr17",
    "load8",
    "load18",
    "mul11",
    "mul20",
    "add12",
    "add21",
    "store13",
    "store22",
    }},



    {"cholesky_u",{"phi0",
    "add9",
    "icmp16",
    "br17",
    "call2",
    "load3",
    "load4",
    "getelementptr5",
    "getelementptr10",
    "load6",
    "load7",
    "load11",
    "load12",
    "mul8",
    "mul13",
    "add14",
    "sub15",
    "phi1",
    }},



    {"doitgen_u",{"phi0",
    "add19",
    "icmp28",
    "br29",
    "call1",
    "load2",
    "load6",
    "load11",
    "load3",
    "load7",
    "getelementptr12",
    "getelementptr22",
    "load4",
    "load8",
    "load13",
    "load23",
    "load5",
    "getelementptr9",
    "load14",
    "load18",
    "getelementptr20",
    "load24",
    "load10",
    "load21",
    "mul15",
    "mul25",
    "add16",
    "add26",
    "store17",
    "store27",
    }},



    {"gemm_u",{"phi0",
    "add17",
    "icmp28",
    "br29",
    "call1",
    "load2",
    "load7",
    "load12",
    "load3",
    "getelementptr8",
    "load13",
    "getelementptr21",
    "getelementptr4",
    "load9",
    "load14",
    "getelementptr18",
    "load22",
    "load25",
    "load5",
    "load10",
    "load19",
    "load23",
    "mul6",
    "mul20",
    "mul11",
    "mul24",
    "add15",
    "add26",
    "store16",
    "store27",
    }},



    {"symm_u",{"phi0",
    "add16",
    "icmp27",
    "br28",
    "call1",
    "load2",
    "load6",
    "load10",
    "getelementptr3",
    "load7",
    "getelementptr11",
    "getelementptr17",
    "getelementptr22",
    "load4",
    "load8",
    "load12",
    "load18",
    "load20",
    "load23",
    "load5",
    "load13",
    "load19",
    "load24",
    "mul9",
    "mul21",
    "add14",
    "add25",
    "store15",
    "store26",
    }},



    {"syrk_u",{"phi0",
    "add13",
    "icmp20",
    "br21",
    "call1",
    "load2",
    "load8",
    "load3",
    "load9",
    "getelementptr4",
    "load10",
    "getelementptr14",
    "load5",
    "load15",
    "mul6",
    "mul16",
    "mul7",
    "mul17",
    "add11",
    "store12",
    "add18",
    "store19",
    }},
    
};

static map<string, vector<Tile>> allocated_tiles_shapes = {  // mapping on 4x4 CGRA  
    {"16-S", 
    {cgra.Tiles[0], cgra.Tiles[1], cgra.Tiles[2], cgra.Tiles[3],
    cgra.Tiles[4], cgra.Tiles[5], cgra.Tiles[6], cgra.Tiles[7],
    cgra.Tiles[8], cgra.Tiles[9], cgra.Tiles[10], cgra.Tiles[11],
    cgra.Tiles[12], cgra.Tiles[13], cgra.Tiles[14], cgra.Tiles[15]}},
};

// referencing 5x5 CGRA static mapping results
static map<string, map<string, map<string, Tile>>> placement_static_Opt2Tile_kernels_architecture = {
    {"Diagonal", { 
        {"atax",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp15",cgra.Tiles[18]},
        {"br16",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load5",cgra.Tiles[12]},
        {"load9",cgra.Tiles[13]},
        {"getelementptr3",cgra.Tiles[21]},
        {"load6",cgra.Tiles[6]},
        {"load10",cgra.Tiles[7]},
        {"load4",cgra.Tiles[16]},
        {"getelementptr7",cgra.Tiles[11]},
        {"load8",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[7]},
        {"add12",cgra.Tiles[8]},
        {"store13",cgra.Tiles[7]},
        }},
        
        {"cholesky",{{"phi0",cgra.Tiles[21]},
        {"add10",cgra.Tiles[23]},
        {"icmp11",cgra.Tiles[17]},
        {"br12",cgra.Tiles[23]},
        {"call2",cgra.Tiles[17]},
        {"load3",cgra.Tiles[18]},
        {"load4",cgra.Tiles[12]},
        {"getelementptr5",cgra.Tiles[3]},
        {"load6",cgra.Tiles[8]},
        {"load7",cgra.Tiles[7]},
        {"mul8",cgra.Tiles[8]},
        {"sub9",cgra.Tiles[13]},
        {"phi1",cgra.Tiles[7]},
        }},
        
        {"doitgen",{{"phi0",cgra.Tiles[21]},
        {"add18",cgra.Tiles[23]},
        {"icmp19",cgra.Tiles[18]},
        {"br20",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load11",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"load7",cgra.Tiles[6]},
        {"getelementptr12",cgra.Tiles[8]},
        {"load4",cgra.Tiles[1]},
        {"load8",cgra.Tiles[11]},
        {"load13",cgra.Tiles[7]},
        {"load5",cgra.Tiles[6]},
        {"getelementptr9",cgra.Tiles[12]},
        {"load14",cgra.Tiles[13]},
        {"load10",cgra.Tiles[8]},
        {"mul15",cgra.Tiles[7]},
        {"add16",cgra.Tiles[8]},
        {"store17",cgra.Tiles[13]},
        }},
        
        {"bicg",{{"phi0",cgra.Tiles[21]},
        {"add23",cgra.Tiles[23]},
        {"icmp24",cgra.Tiles[18]},
        {"br25",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load5",cgra.Tiles[12]},
        {"load7",cgra.Tiles[13]},
        {"load14",cgra.Tiles[3]},
        {"load17",cgra.Tiles[7]},
        {"getelementptr3",cgra.Tiles[21]},
        {"load6",cgra.Tiles[6]},
        {"load8",cgra.Tiles[8]},
        {"load15",cgra.Tiles[7]},
        {"getelementptr18",cgra.Tiles[12]},
        {"load4",cgra.Tiles[16]},
        {"getelementptr9",cgra.Tiles[1]},
        {"load19",cgra.Tiles[11]},
        {"load10",cgra.Tiles[6]},
        {"load16",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[7]},
        {"mul20",cgra.Tiles[8]},
        {"add12",cgra.Tiles[6]},
        {"add21",cgra.Tiles[16]},
        {"store13",cgra.Tiles[11]},
        {"store22",cgra.Tiles[13]},
        }},
        
        {"gemm",{{"phi0",cgra.Tiles[21]},
        {"add17",cgra.Tiles[23]},
        {"icmp18",cgra.Tiles[18]},
        {"br19",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[12]},
        {"load12",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"getelementptr8",cgra.Tiles[8]},
        {"load13",cgra.Tiles[1]},
        {"getelementptr4",cgra.Tiles[6]},
        {"load9",cgra.Tiles[13]},
        {"load14",cgra.Tiles[7]},
        {"load5",cgra.Tiles[11]},
        {"load10",cgra.Tiles[8]},
        {"mul6",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[12]},
        {"add15",cgra.Tiles[16]},
        {"store16",cgra.Tiles[11]},
        }},
        
        {"gemver",{{"phi0",cgra.Tiles[21]},
        {"add21",cgra.Tiles[23]},
        {"icmp22",cgra.Tiles[18]},
        {"br23",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load8",cgra.Tiles[13]},
        {"load13",cgra.Tiles[16]},
        {"load15",cgra.Tiles[7]},
        {"load3",cgra.Tiles[6]},
        {"load7",cgra.Tiles[13]},
        {"getelementptr9",cgra.Tiles[8]},
        {"load14",cgra.Tiles[11]},
        {"getelementptr16",cgra.Tiles[6]},
        {"getelementptr4",cgra.Tiles[1]},
        {"load10",cgra.Tiles[7]},
        {"load17",cgra.Tiles[12]},
        {"load5",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[8]},
        {"mul18",cgra.Tiles[16]},
        {"add12",cgra.Tiles[7]},
        {"add19",cgra.Tiles[11]},
        {"store20",cgra.Tiles[17]},
        }},
        
        {"gesummv",{{"phi0",cgra.Tiles[21]},
        {"add24",cgra.Tiles[23]},
        {"icmp25",cgra.Tiles[18]},
        {"br26",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load10",cgra.Tiles[3]},
        {"load14",cgra.Tiles[13]},
        {"load20",cgra.Tiles[1]},
        {"load3",cgra.Tiles[6]},
        {"getelementptr7",cgra.Tiles[21]},
        {"load11",cgra.Tiles[8]},
        {"load15",cgra.Tiles[8]},
        {"load21",cgra.Tiles[7]},
        {"getelementptr4",cgra.Tiles[11]},
        {"load8",cgra.Tiles[16]},
        {"getelementptr16",cgra.Tiles[13]},
        {"load18",cgra.Tiles[12]},
        {"load5",cgra.Tiles[6]},
        {"load17",cgra.Tiles[17]},
        {"mul9",cgra.Tiles[7]},
        {"mul19",cgra.Tiles[16]},
        {"add12",cgra.Tiles[8]},
        {"add22",cgra.Tiles[17]},
        {"store13",cgra.Tiles[12]},
        {"store23",cgra.Tiles[18]},
        }},
        
        {"mvt",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp15",cgra.Tiles[18]},
        {"br16",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[19]},
        {"load4",cgra.Tiles[11]},
        {"load8",cgra.Tiles[12]},
        {"load3",cgra.Tiles[13]},
        {"getelementptr5",cgra.Tiles[7]},
        {"getelementptr9",cgra.Tiles[6]},
        {"load6",cgra.Tiles[13]},
        {"load10",cgra.Tiles[12]},
        {"load7",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[6]},
        {"add12",cgra.Tiles[11]},
        {"store13",cgra.Tiles[16]},
        }},
        
        {"symm",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp17",cgra.Tiles[18]},
        {"br18",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load10",cgra.Tiles[13]},
        {"getelementptr3",cgra.Tiles[7]},
        {"load7",cgra.Tiles[6]},
        {"getelementptr11",cgra.Tiles[8]},
        {"load4",cgra.Tiles[13]},
        {"load8",cgra.Tiles[11]},
        {"load12",cgra.Tiles[3]},
        {"load5",cgra.Tiles[7]},
        {"load13",cgra.Tiles[8]},
        {"mul9",cgra.Tiles[6]},
        {"add14",cgra.Tiles[12]},
        {"store15",cgra.Tiles[16]},
        }},
        
        {"syrk",{{"phi0",cgra.Tiles[21]},
        {"add13",cgra.Tiles[23]},
        {"icmp14",cgra.Tiles[17]},
        {"br15",cgra.Tiles[23]},
        {"call1",cgra.Tiles[17]},
        {"load2",cgra.Tiles[18]},
        {"load8",cgra.Tiles[11]},
        {"load3",cgra.Tiles[12]},
        {"load9",cgra.Tiles[3]},
        {"getelementptr4",cgra.Tiles[8]},
        {"load10",cgra.Tiles[8]},
        {"load5",cgra.Tiles[1]},
        {"mul6",cgra.Tiles[7]},
        {"mul7",cgra.Tiles[6]},
        {"add11",cgra.Tiles[7]},
        {"store12",cgra.Tiles[6]},
        }},
        
        {"trmm",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp17",cgra.Tiles[18]},
        {"br18",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[3]},
        {"getelementptr3",cgra.Tiles[6]},
        {"load8",cgra.Tiles[8]},
        {"getelementptr11",cgra.Tiles[7]},
        {"load4",cgra.Tiles[12]},
        {"load9",cgra.Tiles[7]},
        {"load12",cgra.Tiles[3]},
        {"load5",cgra.Tiles[6]},
        {"load13",cgra.Tiles[8]},
        {"mul6",cgra.Tiles[11]},
        {"mul10",cgra.Tiles[12]},
        {"add14",cgra.Tiles[13]},
        {"store15",cgra.Tiles[8]},
        }},
        
        {"syr2k",{{"phi0",cgra.Tiles[21]},
        {"add23",cgra.Tiles[23]},
        {"icmp24",cgra.Tiles[18]},
        {"br25",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[12]},
        {"load12",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"load8",cgra.Tiles[6]},
        {"load13",cgra.Tiles[3]},
        {"getelementptr4",cgra.Tiles[1]},
        {"getelementptr9",cgra.Tiles[3]},
        {"load14",cgra.Tiles[8]},
        {"load5",cgra.Tiles[6]},
        {"load10",cgra.Tiles[7]},
        {"load17",cgra.Tiles[8]},
        {"load19",cgra.Tiles[12]},
        {"shl6",cgra.Tiles[11]},
        {"shl18",cgra.Tiles[13]},
        {"mul11",cgra.Tiles[6]},
        {"mul20",cgra.Tiles[17]},
        {"add15",cgra.Tiles[1]},
        {"store16",cgra.Tiles[5]},
        {"add21",cgra.Tiles[11]},
        {"store22",cgra.Tiles[16]},
        }},
        
        {"atax_u",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp23",cgra.Tiles[18]},
        {"br24",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[3]},
        {"load5",cgra.Tiles[11]},
        {"load9",cgra.Tiles[1]},
        {"getelementptr3",cgra.Tiles[1]},
        {"load6",cgra.Tiles[21]},
        {"load10",cgra.Tiles[7]},
        {"getelementptr15",cgra.Tiles[9]},
        {"load19",cgra.Tiles[6]},
        {"load4",cgra.Tiles[7]},
        {"getelementptr7",cgra.Tiles[16]},
        {"load16",cgra.Tiles[8]},
        {"getelementptr17",cgra.Tiles[12]},
        {"load8",cgra.Tiles[11]},
        {"load18",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[16]},
        {"mul20",cgra.Tiles[12]},
        {"add12",cgra.Tiles[8]},
        {"add21",cgra.Tiles[13]},
        {"store13",cgra.Tiles[13]},
        {"store22",cgra.Tiles[8]},
        }},
        
        {"cholesky_u",{{"phi0",cgra.Tiles[21]},
        {"add9",cgra.Tiles[23]},
        {"icmp16",cgra.Tiles[17]},
        {"br17",cgra.Tiles[23]},
        {"call2",cgra.Tiles[12]},
        {"load3",cgra.Tiles[11]},
        {"load4",cgra.Tiles[3]},
        {"getelementptr5",cgra.Tiles[1]},
        {"getelementptr10",cgra.Tiles[9]},
        {"load6",cgra.Tiles[6]},
        {"load7",cgra.Tiles[7]},
        {"load11",cgra.Tiles[8]},
        {"load12",cgra.Tiles[13]},
        {"mul8",cgra.Tiles[6]},
        {"mul13",cgra.Tiles[8]},
        {"add14",cgra.Tiles[11]},
        {"sub15",cgra.Tiles[12]},
        {"phi1",cgra.Tiles[7]},
        }},
        
        {"doitgen_u",{{"phi0",cgra.Tiles[21]},
        {"add19",cgra.Tiles[23]},
        {"icmp28",cgra.Tiles[18]},
        {"br29",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load11",cgra.Tiles[3]},
        {"load3",cgra.Tiles[6]},
        {"load7",cgra.Tiles[13]},
        {"getelementptr12",cgra.Tiles[8]},
        {"getelementptr22",cgra.Tiles[7]},
        {"load4",cgra.Tiles[1]},
        {"load8",cgra.Tiles[3]},
        {"load13",cgra.Tiles[13]},
        {"load23",cgra.Tiles[8]},
        {"load5",cgra.Tiles[6]},
        {"getelementptr9",cgra.Tiles[7]},
        {"load14",cgra.Tiles[12]},
        {"load18",cgra.Tiles[11]},
        {"getelementptr20",cgra.Tiles[13]},
        {"load24",cgra.Tiles[7]},
        {"load10",cgra.Tiles[8]},
        {"load21",cgra.Tiles[8]},
        {"mul15",cgra.Tiles[13]},
        {"mul25",cgra.Tiles[16]},
        {"add16",cgra.Tiles[17]},
        {"add26",cgra.Tiles[12]},
        {"store17",cgra.Tiles[11]},
        {"store27",cgra.Tiles[16]},
        }},
        
        {"gemm_u",{{"phi0",cgra.Tiles[21]},
        {"add17",cgra.Tiles[23]},
        {"icmp28",cgra.Tiles[18]},
        {"br29",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[3]},
        {"load12",cgra.Tiles[12]},
        {"load3",cgra.Tiles[1]},
        {"getelementptr8",cgra.Tiles[8]},
        {"load13",cgra.Tiles[21]},
        {"getelementptr21",cgra.Tiles[7]},
        {"getelementptr4",cgra.Tiles[6]},
        {"load9",cgra.Tiles[13]},
        {"load14",cgra.Tiles[16]},
        {"getelementptr18",cgra.Tiles[12]},
        {"load22",cgra.Tiles[8]},
        {"load25",cgra.Tiles[11]},
        {"load5",cgra.Tiles[7]},
        {"load10",cgra.Tiles[7]},
        {"load19",cgra.Tiles[6]},
        {"load23",cgra.Tiles[13]},
        {"mul6",cgra.Tiles[8]},
        {"mul20",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[13]},
        {"mul24",cgra.Tiles[6]},
        {"add15",cgra.Tiles[8]},
        {"add26",cgra.Tiles[11]},
        {"store16",cgra.Tiles[13]},
        {"store27",cgra.Tiles[5]},
        }},
        
        {"symm_u",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp27",cgra.Tiles[18]},
        {"br28",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[3]},
        {"load6",cgra.Tiles[11]},
        {"load10",cgra.Tiles[1]},
        {"getelementptr3",cgra.Tiles[8]},
        {"load7",cgra.Tiles[21]},
        {"getelementptr11",cgra.Tiles[6]},
        {"getelementptr17",cgra.Tiles[7]},
        {"getelementptr22",cgra.Tiles[12]},
        {"load4",cgra.Tiles[13]},
        {"load8",cgra.Tiles[16]},
        {"load12",cgra.Tiles[1]},
        {"load18",cgra.Tiles[6]},
        {"load20",cgra.Tiles[11]},
        {"load23",cgra.Tiles[3]},
        {"load5",cgra.Tiles[8]},
        {"load13",cgra.Tiles[7]},
        {"load19",cgra.Tiles[12]},
        {"load24",cgra.Tiles[8]},
        {"mul9",cgra.Tiles[13]},
        {"mul21",cgra.Tiles[16]},
        {"add14",cgra.Tiles[7]},
        {"add25",cgra.Tiles[13]},
        {"store15",cgra.Tiles[11]},
        {"store26",cgra.Tiles[9]},
        }},
        
        {"syrk_u",{{"phi0",cgra.Tiles[21]},
        {"add13",cgra.Tiles[23]},
        {"icmp20",cgra.Tiles[17]},
        {"br21",cgra.Tiles[23]},
        {"call1",cgra.Tiles[12]},
        {"load2",cgra.Tiles[11]},
        {"load8",cgra.Tiles[13]},
        {"load3",cgra.Tiles[3]},
        {"load9",cgra.Tiles[1]},
        {"getelementptr4",cgra.Tiles[8]},
        {"load10",cgra.Tiles[6]},
        {"getelementptr14",cgra.Tiles[7]},
        {"load5",cgra.Tiles[3]},
        {"load15",cgra.Tiles[1]},
        {"mul6",cgra.Tiles[8]},
        {"mul16",cgra.Tiles[7]},
        {"mul7",cgra.Tiles[11]},
        {"mul17",cgra.Tiles[6]},
        {"add11",cgra.Tiles[21]},
        {"store12",cgra.Tiles[16]},
        {"add18",cgra.Tiles[12]},
        {"store19",cgra.Tiles[16]},
        }},
    }},

    {"Orthogonal", { 
        {"atax",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp15",cgra.Tiles[18]},
        {"br16",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load5",cgra.Tiles[12]},
        {"load9",cgra.Tiles[13]},
        {"getelementptr3",cgra.Tiles[21]},
        {"load6",cgra.Tiles[6]},
        {"load10",cgra.Tiles[7]},
        {"load4",cgra.Tiles[16]},
        {"getelementptr7",cgra.Tiles[11]},
        {"load8",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[7]},
        {"add12",cgra.Tiles[8]},
        {"store13",cgra.Tiles[7]},
        }},
        
        {"cholesky",{{"phi0",cgra.Tiles[21]},
        {"add10",cgra.Tiles[23]},
        {"icmp11",cgra.Tiles[17]},
        {"br12",cgra.Tiles[23]},
        {"call2",cgra.Tiles[17]},
        {"load3",cgra.Tiles[18]},
        {"load4",cgra.Tiles[12]},
        {"getelementptr5",cgra.Tiles[3]},
        {"load6",cgra.Tiles[8]},
        {"load7",cgra.Tiles[7]},
        {"mul8",cgra.Tiles[8]},
        {"sub9",cgra.Tiles[13]},
        {"phi1",cgra.Tiles[7]},
        }},
        
        {"doitgen",{{"phi0",cgra.Tiles[21]},
        {"add18",cgra.Tiles[23]},
        {"icmp19",cgra.Tiles[18]},
        {"br20",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load11",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"load7",cgra.Tiles[6]},
        {"getelementptr12",cgra.Tiles[8]},
        {"load4",cgra.Tiles[1]},
        {"load8",cgra.Tiles[11]},
        {"load13",cgra.Tiles[7]},
        {"load5",cgra.Tiles[6]},
        {"getelementptr9",cgra.Tiles[12]},
        {"load14",cgra.Tiles[13]},
        {"load10",cgra.Tiles[8]},
        {"mul15",cgra.Tiles[7]},
        {"add16",cgra.Tiles[8]},
        {"store17",cgra.Tiles[13]},
        }},
        
        {"bicg",{{"phi0",cgra.Tiles[21]},
        {"add23",cgra.Tiles[23]},
        {"icmp24",cgra.Tiles[18]},
        {"br25",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load5",cgra.Tiles[12]},
        {"load7",cgra.Tiles[13]},
        {"load14",cgra.Tiles[3]},
        {"load17",cgra.Tiles[7]},
        {"getelementptr3",cgra.Tiles[21]},
        {"load6",cgra.Tiles[6]},
        {"load8",cgra.Tiles[8]},
        {"load15",cgra.Tiles[7]},
        {"getelementptr18",cgra.Tiles[12]},
        {"load4",cgra.Tiles[16]},
        {"getelementptr9",cgra.Tiles[1]},
        {"load19",cgra.Tiles[11]},
        {"load10",cgra.Tiles[6]},
        {"load16",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[7]},
        {"mul20",cgra.Tiles[8]},
        {"add12",cgra.Tiles[6]},
        {"add21",cgra.Tiles[16]},
        {"store13",cgra.Tiles[11]},
        {"store22",cgra.Tiles[13]},
        }},
        
        {"gemm",{{"phi0",cgra.Tiles[21]},
        {"add17",cgra.Tiles[23]},
        {"icmp18",cgra.Tiles[18]},
        {"br19",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[12]},
        {"load12",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"getelementptr8",cgra.Tiles[8]},
        {"load13",cgra.Tiles[1]},
        {"getelementptr4",cgra.Tiles[6]},
        {"load9",cgra.Tiles[13]},
        {"load14",cgra.Tiles[7]},
        {"load5",cgra.Tiles[11]},
        {"load10",cgra.Tiles[8]},
        {"mul6",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[12]},
        {"add15",cgra.Tiles[16]},
        {"store16",cgra.Tiles[11]},
        }},
        
        {"gemver",{{"phi0",cgra.Tiles[21]},
        {"add21",cgra.Tiles[23]},
        {"icmp22",cgra.Tiles[18]},
        {"br23",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load8",cgra.Tiles[13]},
        {"load13",cgra.Tiles[16]},
        {"load15",cgra.Tiles[7]},
        {"load3",cgra.Tiles[6]},
        {"load7",cgra.Tiles[13]},
        {"getelementptr9",cgra.Tiles[8]},
        {"load14",cgra.Tiles[11]},
        {"getelementptr16",cgra.Tiles[6]},
        {"getelementptr4",cgra.Tiles[1]},
        {"load10",cgra.Tiles[7]},
        {"load17",cgra.Tiles[12]},
        {"load5",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[8]},
        {"mul18",cgra.Tiles[16]},
        {"add12",cgra.Tiles[7]},
        {"add19",cgra.Tiles[11]},
        {"store20",cgra.Tiles[17]},
        }},
        
        {"gesummv",{{"phi0",cgra.Tiles[21]},
        {"add24",cgra.Tiles[23]},
        {"icmp25",cgra.Tiles[18]},
        {"br26",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load10",cgra.Tiles[3]},
        {"load14",cgra.Tiles[13]},
        {"load20",cgra.Tiles[1]},
        {"load3",cgra.Tiles[6]},
        {"getelementptr7",cgra.Tiles[21]},
        {"load11",cgra.Tiles[8]},
        {"load15",cgra.Tiles[8]},
        {"load21",cgra.Tiles[7]},
        {"getelementptr4",cgra.Tiles[11]},
        {"load8",cgra.Tiles[16]},
        {"getelementptr16",cgra.Tiles[13]},
        {"load18",cgra.Tiles[12]},
        {"load5",cgra.Tiles[6]},
        {"load17",cgra.Tiles[17]},
        {"mul9",cgra.Tiles[7]},
        {"mul19",cgra.Tiles[16]},
        {"add12",cgra.Tiles[8]},
        {"add22",cgra.Tiles[17]},
        {"store13",cgra.Tiles[12]},
        {"store23",cgra.Tiles[18]},
        }},
        
        {"mvt",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp15",cgra.Tiles[18]},
        {"br16",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[19]},
        {"load4",cgra.Tiles[11]},
        {"load8",cgra.Tiles[12]},
        {"load3",cgra.Tiles[13]},
        {"getelementptr5",cgra.Tiles[7]},
        {"getelementptr9",cgra.Tiles[6]},
        {"load6",cgra.Tiles[13]},
        {"load10",cgra.Tiles[12]},
        {"load7",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[6]},
        {"add12",cgra.Tiles[11]},
        {"store13",cgra.Tiles[16]},
        }},
        
        {"symm",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp17",cgra.Tiles[18]},
        {"br18",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load10",cgra.Tiles[13]},
        {"getelementptr3",cgra.Tiles[7]},
        {"load7",cgra.Tiles[6]},
        {"getelementptr11",cgra.Tiles[8]},
        {"load4",cgra.Tiles[13]},
        {"load8",cgra.Tiles[11]},
        {"load12",cgra.Tiles[3]},
        {"load5",cgra.Tiles[7]},
        {"load13",cgra.Tiles[8]},
        {"mul9",cgra.Tiles[6]},
        {"add14",cgra.Tiles[12]},
        {"store15",cgra.Tiles[16]},
        }},
        
        {"syrk",{{"phi0",cgra.Tiles[21]},
        {"add13",cgra.Tiles[23]},
        {"icmp14",cgra.Tiles[17]},
        {"br15",cgra.Tiles[23]},
        {"call1",cgra.Tiles[17]},
        {"load2",cgra.Tiles[18]},
        {"load8",cgra.Tiles[11]},
        {"load3",cgra.Tiles[12]},
        {"load9",cgra.Tiles[3]},
        {"getelementptr4",cgra.Tiles[8]},
        {"load10",cgra.Tiles[8]},
        {"load5",cgra.Tiles[1]},
        {"mul6",cgra.Tiles[7]},
        {"mul7",cgra.Tiles[6]},
        {"add11",cgra.Tiles[7]},
        {"store12",cgra.Tiles[6]},
        }},
        
        {"trmm",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp17",cgra.Tiles[18]},
        {"br18",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[3]},
        {"getelementptr3",cgra.Tiles[6]},
        {"load8",cgra.Tiles[8]},
        {"getelementptr11",cgra.Tiles[7]},
        {"load4",cgra.Tiles[12]},
        {"load9",cgra.Tiles[7]},
        {"load12",cgra.Tiles[3]},
        {"load5",cgra.Tiles[6]},
        {"load13",cgra.Tiles[8]},
        {"mul6",cgra.Tiles[11]},
        {"mul10",cgra.Tiles[12]},
        {"add14",cgra.Tiles[13]},
        {"store15",cgra.Tiles[8]},
        }},
        
        {"syr2k",{{"phi0",cgra.Tiles[21]},
        {"add23",cgra.Tiles[23]},
        {"icmp24",cgra.Tiles[18]},
        {"br25",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[12]},
        {"load12",cgra.Tiles[13]},
        {"load3",cgra.Tiles[7]},
        {"load8",cgra.Tiles[6]},
        {"load13",cgra.Tiles[3]},
        {"getelementptr4",cgra.Tiles[1]},
        {"getelementptr9",cgra.Tiles[3]},
        {"load14",cgra.Tiles[8]},
        {"load5",cgra.Tiles[6]},
        {"load10",cgra.Tiles[7]},
        {"load17",cgra.Tiles[8]},
        {"load19",cgra.Tiles[12]},
        {"shl6",cgra.Tiles[11]},
        {"shl18",cgra.Tiles[13]},
        {"mul11",cgra.Tiles[6]},
        {"mul20",cgra.Tiles[17]},
        {"add15",cgra.Tiles[1]},
        {"store16",cgra.Tiles[5]},
        {"add21",cgra.Tiles[11]},
        {"store22",cgra.Tiles[16]},
        }},
        
        {"atax_u",{{"phi0",cgra.Tiles[21]},
        {"add14",cgra.Tiles[23]},
        {"icmp23",cgra.Tiles[18]},
        {"br24",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[3]},
        {"load5",cgra.Tiles[11]},
        {"load9",cgra.Tiles[1]},
        {"getelementptr3",cgra.Tiles[1]},
        {"load6",cgra.Tiles[21]},
        {"load10",cgra.Tiles[7]},
        {"getelementptr15",cgra.Tiles[9]},
        {"load19",cgra.Tiles[6]},
        {"load4",cgra.Tiles[7]},
        {"getelementptr7",cgra.Tiles[16]},
        {"load16",cgra.Tiles[8]},
        {"getelementptr17",cgra.Tiles[12]},
        {"load8",cgra.Tiles[11]},
        {"load18",cgra.Tiles[6]},
        {"mul11",cgra.Tiles[16]},
        {"mul20",cgra.Tiles[12]},
        {"add12",cgra.Tiles[8]},
        {"add21",cgra.Tiles[13]},
        {"store13",cgra.Tiles[13]},
        {"store22",cgra.Tiles[8]},
        }},
        
        {"cholesky_u",{{"phi0",cgra.Tiles[21]},
        {"add9",cgra.Tiles[23]},
        {"icmp16",cgra.Tiles[17]},
        {"br17",cgra.Tiles[23]},
        {"call2",cgra.Tiles[12]},
        {"load3",cgra.Tiles[11]},
        {"load4",cgra.Tiles[3]},
        {"getelementptr5",cgra.Tiles[1]},
        {"getelementptr10",cgra.Tiles[9]},
        {"load6",cgra.Tiles[6]},
        {"load7",cgra.Tiles[7]},
        {"load11",cgra.Tiles[8]},
        {"load12",cgra.Tiles[13]},
        {"mul8",cgra.Tiles[6]},
        {"mul13",cgra.Tiles[8]},
        {"add14",cgra.Tiles[11]},
        {"sub15",cgra.Tiles[12]},
        {"phi1",cgra.Tiles[7]},
        }},
        
        {"doitgen_u",{{"phi0",cgra.Tiles[21]},
        {"add19",cgra.Tiles[23]},
        {"icmp28",cgra.Tiles[18]},
        {"br29",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load6",cgra.Tiles[12]},
        {"load11",cgra.Tiles[3]},
        {"load3",cgra.Tiles[6]},
        {"load7",cgra.Tiles[13]},
        {"getelementptr12",cgra.Tiles[8]},
        {"getelementptr22",cgra.Tiles[7]},
        {"load4",cgra.Tiles[1]},
        {"load8",cgra.Tiles[3]},
        {"load13",cgra.Tiles[13]},
        {"load23",cgra.Tiles[8]},
        {"load5",cgra.Tiles[6]},
        {"getelementptr9",cgra.Tiles[7]},
        {"load14",cgra.Tiles[12]},
        {"load18",cgra.Tiles[11]},
        {"getelementptr20",cgra.Tiles[13]},
        {"load24",cgra.Tiles[7]},
        {"load10",cgra.Tiles[8]},
        {"load21",cgra.Tiles[8]},
        {"mul15",cgra.Tiles[13]},
        {"mul25",cgra.Tiles[16]},
        {"add16",cgra.Tiles[17]},
        {"add26",cgra.Tiles[12]},
        {"store17",cgra.Tiles[11]},
        {"store27",cgra.Tiles[16]},
        }},
        
        {"gemm_u",{{"phi0",cgra.Tiles[21]},
        {"add17",cgra.Tiles[23]},
        {"icmp28",cgra.Tiles[18]},
        {"br29",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[11]},
        {"load7",cgra.Tiles[3]},
        {"load12",cgra.Tiles[12]},
        {"load3",cgra.Tiles[1]},
        {"getelementptr8",cgra.Tiles[8]},
        {"load13",cgra.Tiles[21]},
        {"getelementptr21",cgra.Tiles[7]},
        {"getelementptr4",cgra.Tiles[6]},
        {"load9",cgra.Tiles[13]},
        {"load14",cgra.Tiles[16]},
        {"getelementptr18",cgra.Tiles[12]},
        {"load22",cgra.Tiles[8]},
        {"load25",cgra.Tiles[11]},
        {"load5",cgra.Tiles[7]},
        {"load10",cgra.Tiles[7]},
        {"load19",cgra.Tiles[6]},
        {"load23",cgra.Tiles[13]},
        {"mul6",cgra.Tiles[8]},
        {"mul20",cgra.Tiles[7]},
        {"mul11",cgra.Tiles[13]},
        {"mul24",cgra.Tiles[6]},
        {"add15",cgra.Tiles[8]},
        {"add26",cgra.Tiles[11]},
        {"store16",cgra.Tiles[13]},
        {"store27",cgra.Tiles[5]},
        }},
        
        {"symm_u",{{"phi0",cgra.Tiles[21]},
        {"add16",cgra.Tiles[23]},
        {"icmp27",cgra.Tiles[18]},
        {"br28",cgra.Tiles[23]},
        {"call1",cgra.Tiles[18]},
        {"load2",cgra.Tiles[3]},
        {"load6",cgra.Tiles[11]},
        {"load10",cgra.Tiles[1]},
        {"getelementptr3",cgra.Tiles[8]},
        {"load7",cgra.Tiles[21]},
        {"getelementptr11",cgra.Tiles[6]},
        {"getelementptr17",cgra.Tiles[7]},
        {"getelementptr22",cgra.Tiles[12]},
        {"load4",cgra.Tiles[13]},
        {"load8",cgra.Tiles[16]},
        {"load12",cgra.Tiles[1]},
        {"load18",cgra.Tiles[6]},
        {"load20",cgra.Tiles[11]},
        {"load23",cgra.Tiles[3]},
        {"load5",cgra.Tiles[8]},
        {"load13",cgra.Tiles[7]},
        {"load19",cgra.Tiles[12]},
        {"load24",cgra.Tiles[8]},
        {"mul9",cgra.Tiles[13]},
        {"mul21",cgra.Tiles[16]},
        {"add14",cgra.Tiles[7]},
        {"add25",cgra.Tiles[13]},
        {"store15",cgra.Tiles[11]},
        {"store26",cgra.Tiles[9]},
        }},
        
        {"syrk_u",{{"phi0",cgra.Tiles[21]},
        {"add13",cgra.Tiles[23]},
        {"icmp20",cgra.Tiles[17]},
        {"br21",cgra.Tiles[23]},
        {"call1",cgra.Tiles[12]},
        {"load2",cgra.Tiles[11]},
        {"load8",cgra.Tiles[13]},
        {"load3",cgra.Tiles[3]},
        {"load9",cgra.Tiles[1]},
        {"getelementptr4",cgra.Tiles[8]},
        {"load10",cgra.Tiles[6]},
        {"getelementptr14",cgra.Tiles[7]},
        {"load5",cgra.Tiles[3]},
        {"load15",cgra.Tiles[1]},
        {"mul6",cgra.Tiles[8]},
        {"mul16",cgra.Tiles[7]},
        {"mul7",cgra.Tiles[11]},
        {"mul17",cgra.Tiles[6]},
        {"add11",cgra.Tiles[21]},
        {"store12",cgra.Tiles[16]},
        {"add18",cgra.Tiles[12]},
        {"store19",cgra.Tiles[16]},
        }},
    }},
    
};

static map<string, map<string, int>> placement_done_kernels = {
    {"atax",{{"phi0", 0},
    {"add14", 0},
    {"icmp15", 0},
    {"br16", 0},
    {"call1", 0},
    {"load2", 0},
    {"load5", 0},
    {"load9", 0},
    {"getelementptr3", 0},
    {"load6", 0},
    {"load10", 0},
    {"load4", 0},
    {"getelementptr7", 0},
    {"load8", 0},
    {"mul11", 0},
    {"add12", 0},
    {"store13", 0},
    }},



    {"cholesky",{{"phi0", 0},
    {"add10", 0},
    {"icmp11", 0},
    {"br12", 0},
    {"call2", 0},
    {"load3", 0},
    {"load4", 0},
    {"getelementptr5", 0},
    {"load6", 0},
    {"load7", 0},
    {"mul8", 0},
    {"sub9", 0},
    {"phi1", 0},
    }},



    {"doitgen",{{"phi0", 0},
    {"add18", 0},
    {"icmp19", 0},
    {"br20", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load11", 0},
    {"load3", 0},
    {"load7", 0},
    {"getelementptr12", 0},
    {"load4", 0},
    {"load8", 0},
    {"load13", 0},
    {"load5", 0},
    {"getelementptr9", 0},
    {"load14", 0},
    {"load10", 0},
    {"mul15", 0},
    {"add16", 0},
    {"store17", 0},
    }},



    {"bicg",{{"phi0", 0},
    {"add23", 0},
    {"icmp24", 0},
    {"br25", 0},
    {"call1", 0},
    {"load2", 0},
    {"load5", 0},
    {"load7", 0},
    {"load14", 0},
    {"load17", 0},
    {"getelementptr3", 0},
    {"load6", 0},
    {"load8", 0},
    {"load15", 0},
    {"getelementptr18", 0},
    {"load4", 0},
    {"getelementptr9", 0},
    {"load19", 0},
    {"load10", 0},
    {"load16", 0},
    {"mul11", 0},
    {"mul20", 0},
    {"add12", 0},
    {"add21", 0},
    {"store13", 0},
    {"store22", 0},
    }},



    {"gemm",{{"phi0", 0},
    {"add17", 0},
    {"icmp18", 0},
    {"br19", 0},
    {"call1", 0},
    {"load2", 0},
    {"load7", 0},
    {"load12", 0},
    {"load3", 0},
    {"getelementptr8", 0},
    {"load13", 0},
    {"getelementptr4", 0},
    {"load9", 0},
    {"load14", 0},
    {"load5", 0},
    {"load10", 0},
    {"mul6", 0},
    {"mul11", 0},
    {"add15", 0},
    {"store16", 0},
    }},



    {"gemver",{{"phi0", 0},
    {"add21", 0},
    {"icmp22", 0},
    {"br23", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load8", 0},
    {"load13", 0},
    {"load15", 0},
    {"load3", 0},
    {"load7", 0},
    {"getelementptr9", 0},
    {"load14", 0},
    {"getelementptr16", 0},
    {"getelementptr4", 0},
    {"load10", 0},
    {"load17", 0},
    {"load5", 0},
    {"mul11", 0},
    {"mul18", 0},
    {"add12", 0},
    {"add19", 0},
    {"store20", 0},
    }},



    {"gesummv",{{"phi0", 0},
    {"add24", 0},
    {"icmp25", 0},
    {"br26", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load10", 0},
    {"load14", 0},
    {"load20", 0},
    {"load3", 0},
    {"getelementptr7", 0},
    {"load11", 0},
    {"load15", 0},
    {"load21", 0},
    {"getelementptr4", 0},
    {"load8", 0},
    {"getelementptr16", 0},
    {"load18", 0},
    {"load5", 0},
    {"load17", 0},
    {"mul9", 0},
    {"mul19", 0},
    {"add12", 0},
    {"add22", 0},
    {"store13", 0},
    {"store23", 0},
    }},



    {"mvt",{{"phi0", 0},
    {"add14", 0},
    {"icmp15", 0},
    {"br16", 0},
    {"call1", 0},
    {"load2", 0},
    {"load4", 0},
    {"load8", 0},
    {"load3", 0},
    {"getelementptr5", 0},
    {"getelementptr9", 0},
    {"load6", 0},
    {"load10", 0},
    {"load7", 0},
    {"mul11", 0},
    {"add12", 0},
    {"store13", 0},
    }},



    {"symm",{{"phi0", 0},
    {"add16", 0},
    {"icmp17", 0},
    {"br18", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load10", 0},
    {"getelementptr3", 0},
    {"load7", 0},
    {"getelementptr11", 0},
    {"load4", 0},
    {"load8", 0},
    {"load12", 0},
    {"load5", 0},
    {"load13", 0},
    {"mul9", 0},
    {"add14", 0},
    {"store15", 0},
    }},



    {"syrk",{{"phi0", 0},
    {"add13", 0},
    {"icmp14", 0},
    {"br15", 0},
    {"call1", 0},
    {"load2", 0},
    {"load8", 0},
    {"load3", 0},
    {"load9", 0},
    {"getelementptr4", 0},
    {"load10", 0},
    {"load5", 0},
    {"mul6", 0},
    {"mul7", 0},
    {"add11", 0},
    {"store12", 0},
    }},



    {"trmm",{{"phi0", 0},
    {"add16", 0},
    {"icmp17", 0},
    {"br18", 0},
    {"call1", 0},
    {"load2", 0},
    {"load7", 0},
    {"getelementptr3", 0},
    {"load8", 0},
    {"getelementptr11", 0},
    {"load4", 0},
    {"load9", 0},
    {"load12", 0},
    {"load5", 0},
    {"load13", 0},
    {"mul6", 0},
    {"mul10", 0},
    {"add14", 0},
    {"store15", 0},
    }},



    {"syr2k",{{"phi0", 0},
    {"add23", 0},
    {"icmp24", 0},
    {"br25", 0},
    {"call1", 0},
    {"load2", 0},
    {"load7", 0},
    {"load12", 0},
    {"load3", 0},
    {"load8", 0},
    {"load13", 0},
    {"getelementptr4", 0},
    {"getelementptr9", 0},
    {"load14", 0},
    {"load5", 0},
    {"load10", 0},
    {"load17", 0},
    {"load19", 0},
    {"shl6", 0},
    {"shl18", 0},
    {"mul11", 0},
    {"mul20", 0},
    {"add15", 0},
    {"store16", 0},
    {"add21", 0},
    {"store22", 0},
    }},



    {"atax_u",{{"phi0", 0},
    {"add14", 0},
    {"icmp23", 0},
    {"br24", 0},
    {"call1", 0},
    {"load2", 0},
    {"load5", 0},
    {"load9", 0},
    {"getelementptr3", 0},
    {"load6", 0},
    {"load10", 0},
    {"getelementptr15", 0},
    {"load19", 0},
    {"load4", 0},
    {"getelementptr7", 0},
    {"load16", 0},
    {"getelementptr17", 0},
    {"load8", 0},
    {"load18", 0},
    {"mul11", 0},
    {"mul20", 0},
    {"add12", 0},
    {"add21", 0},
    {"store13", 0},
    {"store22", 0},
    }},



    {"cholesky_u",{{"phi0", 0},
    {"add9", 0},
    {"icmp16", 0},
    {"br17", 0},
    {"call2", 0},
    {"load3", 0},
    {"load4", 0},
    {"getelementptr5", 0},
    {"getelementptr10", 0},
    {"load6", 0},
    {"load7", 0},
    {"load11", 0},
    {"load12", 0},
    {"mul8", 0},
    {"mul13", 0},
    {"add14", 0},
    {"sub15", 0},
    {"phi1", 0},
    }},



    {"doitgen_u",{{"phi0", 0},
    {"add19", 0},
    {"icmp28", 0},
    {"br29", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load11", 0},
    {"load3", 0},
    {"load7", 0},
    {"getelementptr12", 0},
    {"getelementptr22", 0},
    {"load4", 0},
    {"load8", 0},
    {"load13", 0},
    {"load23", 0},
    {"load5", 0},
    {"getelementptr9", 0},
    {"load14", 0},
    {"load18", 0},
    {"getelementptr20", 0},
    {"load24", 0},
    {"load10", 0},
    {"load21", 0},
    {"mul15", 0},
    {"mul25", 0},
    {"add16", 0},
    {"add26", 0},
    {"store17", 0},
    {"store27", 0},
    }},



    {"gemm_u",{{"phi0", 0},
    {"add17", 0},
    {"icmp28", 0},
    {"br29", 0},
    {"call1", 0},
    {"load2", 0},
    {"load7", 0},
    {"load12", 0},
    {"load3", 0},
    {"getelementptr8", 0},
    {"load13", 0},
    {"getelementptr21", 0},
    {"getelementptr4", 0},
    {"load9", 0},
    {"load14", 0},
    {"getelementptr18", 0},
    {"load22", 0},
    {"load25", 0},
    {"load5", 0},
    {"load10", 0},
    {"load19", 0},
    {"load23", 0},
    {"mul6", 0},
    {"mul20", 0},
    {"mul11", 0},
    {"mul24", 0},
    {"add15", 0},
    {"add26", 0},
    {"store16", 0},
    {"store27", 0},
    }},



    {"symm_u",{{"phi0", 0},
    {"add16", 0},
    {"icmp27", 0},
    {"br28", 0},
    {"call1", 0},
    {"load2", 0},
    {"load6", 0},
    {"load10", 0},
    {"getelementptr3", 0},
    {"load7", 0},
    {"getelementptr11", 0},
    {"getelementptr17", 0},
    {"getelementptr22", 0},
    {"load4", 0},
    {"load8", 0},
    {"load12", 0},
    {"load18", 0},
    {"load20", 0},
    {"load23", 0},
    {"load5", 0},
    {"load13", 0},
    {"load19", 0},
    {"load24", 0},
    {"mul9", 0},
    {"mul21", 0},
    {"add14", 0},
    {"add25", 0},
    {"store15", 0},
    {"store26", 0},
    }},



    {"syrk_u",{{"phi0", 0},
    {"add13", 0},
    {"icmp20", 0},
    {"br21", 0},
    {"call1", 0},
    {"load2", 0},
    {"load8", 0},
    {"load3", 0},
    {"load9", 0},
    {"getelementptr4", 0},
    {"load10", 0},
    {"getelementptr14", 0},
    {"load5", 0},
    {"load15", 0},
    {"mul6", 0},
    {"mul16", 0},
    {"mul7", 0},
    {"mul17", 0},
    {"add11", 0},
    {"store12", 0},
    {"add18", 0},
    {"store19", 0},
    }},

};

static map<string, map<string, vector<string>>> dependency_predecessors_kernels = {
    {"atax",{{"phi0", {"add14", "br16"}},
    {"add14", {"phi0"}},
    {"icmp15", {"add14", "br16"}},
    {"br16", {"icmp15"}},
    {"call1", {"br16"}},
    {"load2", {"br16"}},
    {"load5", {"br16"}},
    {"load9", {"br16"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load6", {"load5"}},
    {"load10", {"load9"}},
    {"load4", {"getelementptr3"}},
    {"getelementptr7", {"load6", "phi0"}},
    {"load8", {"getelementptr7"}},
    {"mul11", {"load10", "load8"}},
    {"add12", {"mul11", "load4"}},
    {"store13", {"add12", "getelementptr3"}},
    }},



    {"cholesky",{{"phi0", {"add10", "br12"}},
    {"add10", {"phi0"}},
    {"icmp11", {"add10", "br12"}},
    {"br12", {"icmp11"}},
    {"call2", {"br12"}},
    {"load3", {"br12"}},
    {"load4", {"load3"}},
    {"getelementptr5", {"load4", "phi0"}},
    {"load6", {"getelementptr5"}},
    {"load7", {"getelementptr5"}},
    {"mul8", {"load7", "load6"}},
    {"sub9", {"phi1", "mul8"}},
    {"phi1", {"sub9", "br12"}},
    }},



    {"doitgen",{{"phi0", {"add18", "br20"}},
    {"add18", {"phi0"}},
    {"icmp19", {"add18", "br20"}},
    {"br20", {"icmp19"}},
    {"call1", {"br20"}},
    {"load2", {"br20"}},
    {"load6", {"br20"}},
    {"load11", {"br20"}},
    {"load3", {"load2"}},
    {"load7", {"load6"}},
    {"getelementptr12", {"load11", "phi0"}},
    {"load4", {"load3"}},
    {"load8", {"load7"}},
    {"load13", {"getelementptr12"}},
    {"load5", {"load4"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load14", {"load13"}},
    {"load10", {"getelementptr9"}},
    {"mul15", {"load14", "load10"}},
    {"add16", {"mul15", "load5"}},
    {"store17", {"add16", "load4"}},
    }},



    {"bicg",{{"phi0", {"add23", "br25"}},
    {"add23", {"phi0"}},
    {"icmp24", {"add23", "br25"}},
    {"br25", {"icmp24"}},
    {"call1", {"br25"}},
    {"load2", {"br25"}},
    {"load5", {"br25"}},
    {"load7", {"br25"}},
    {"load14", {"br25"}},
    {"load17", {"br25"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load6", {"load5"}},
    {"load8", {"load7"}},
    {"load15", {"load14"}},
    {"getelementptr18", {"load17", "phi0"}},
    {"load4", {"getelementptr3"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load19", {"getelementptr18"}},
    {"load10", {"getelementptr9"}},
    {"load16", {"getelementptr9"}},
    {"mul11", {"load10", "load6"}},
    {"mul20", {"load19", "load16"}},
    {"add12", {"mul11", "load4"}},
    {"add21", {"mul20", "load15"}},
    {"store13", {"add12", "getelementptr3"}},
    {"store22", {"add21", "load14"}},
    }},



    {"gemm",{{"phi0", {"add17", "br19"}},
    {"add17", {"phi0"}},
    {"icmp18", {"add17", "br19"}},
    {"br19", {"icmp18"}},
    {"call1", {"br19"}},
    {"load2", {"br19"}},
    {"load7", {"br19"}},
    {"load12", {"br19"}},
    {"load3", {"load2"}},
    {"getelementptr8", {"load7", "phi0"}},
    {"load13", {"load12"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load9", {"getelementptr8"}},
    {"load14", {"load13"}},
    {"load5", {"getelementptr4"}},
    {"load10", {"load9"}},
    {"mul6", {"load5"}},
    {"mul11", {"mul6", "load10"}},
    {"add15", {"load14", "mul11"}},
    {"store16", {"add15", "load13"}},
    }},



    {"gemver",{{"phi0", {"add21", "br23"}},
    {"add21", {"phi0"}},
    {"icmp22", {"add21", "br23"}},
    {"br23", {"icmp22"}},
    {"call1", {"br23"}},
    {"load2", {"br23"}},
    {"load6", {"br23"}},
    {"load8", {"br23"}},
    {"load13", {"br23"}},
    {"load15", {"br23"}},
    {"load3", {"load2"}},
    {"load7", {"load6"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load14", {"load13"}},
    {"getelementptr16", {"load15", "phi0"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load10", {"getelementptr9"}},
    {"load17", {"getelementptr16"}},
    {"load5", {"getelementptr4"}},
    {"mul11", {"load10", "load7"}},
    {"mul18", {"load17", "load14"}},
    {"add12", {"mul11", "load5"}},
    {"add19", {"add12", "mul18"}},
    {"store20", {"add19", "getelementptr4"}},
    }},



    {"gesummv",{{"phi0", {"add24", "br26"}},
    {"add24", {"phi0"}},
    {"icmp25", {"add24", "br26"}},
    {"br26", {"icmp25"}},
    {"call1", {"br26"}},
    {"load2", {"br26"}},
    {"load6", {"br26"}},
    {"load10", {"br26"}},
    {"load14", {"br26"}},
    {"load20", {"br26"}},
    {"load3", {"load2"}},
    {"getelementptr7", {"load6", "phi0"}},
    {"load11", {"load10"}},
    {"load15", {"load14"}},
    {"load21", {"load20"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load8", {"getelementptr7"}},
    {"getelementptr16", {"load15", "phi0"}},
    {"load18", {"getelementptr7"}},
    {"load5", {"getelementptr4"}},
    {"load17", {"getelementptr16"}},
    {"mul9", {"load8", "load5"}},
    {"mul19", {"load18", "load17"}},
    {"add12", {"load11", "mul9"}},
    {"add22", {"load21", "mul19"}},
    {"store13", {"add12", "load10"}},
    {"store23", {"add22", "load20"}},
    }},



    {"mvt",{{"phi0", {"add14", "br16"}},
    {"add14", {"phi0"}},
    {"icmp15", {"add14", "br16"}},
    {"br16", {"icmp15"}},
    {"call1", {"br16"}},
    {"load2", {"br16"}},
    {"load4", {"br16"}},
    {"load8", {"br16"}},
    {"load3", {"load2"}},
    {"getelementptr5", {"load4", "phi0"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load6", {"getelementptr5"}},
    {"load10", {"getelementptr9"}},
    {"load7", {"load6"}},
    {"mul11", {"load10", "load7"}},
    {"add12", {"mul11", "load3"}},
    {"store13", {"add12", "load2"}},
    }},



    {"symm",{{"phi0", {"add16", "br18"}},
    {"add16", {"phi0"}},
    {"icmp17", {"add16", "br18"}},
    {"br18", {"icmp17"}},
    {"call1", {"br18"}},
    {"load2", {"br18"}},
    {"load6", {"br18"}},
    {"load10", {"br18"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load7", {"load6"}},
    {"getelementptr11", {"load10", "phi0"}},
    {"load4", {"getelementptr3"}},
    {"load8", {"load7"}},
    {"load12", {"getelementptr11"}},
    {"load5", {"load4"}},
    {"load13", {"load12"}},
    {"mul9", {"load8", "load5"}},
    {"add14", {"load13", "mul9"}},
    {"store15", {"add14", "load12"}},
    }},



    {"syrk",{{"phi0", {"add13", "br15"}},
    {"add13", {"phi0"}},
    {"icmp14", {"add13", "br15"}},
    {"br15", {"icmp14"}},
    {"call1", {"br15"}},
    {"load2", {"br15"}},
    {"load8", {"br15"}},
    {"load3", {"load2"}},
    {"load9", {"load8"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load10", {"load9"}},
    {"load5", {"getelementptr4"}},
    {"mul6", {"load5"}},
    {"mul7", {"mul6", "load5"}},
    {"add11", {"load10", "mul7"}},
    {"store12", {"add11", "load9"}},
    }},



    {"trmm",{{"phi0", {"add16", "br18"}},
    {"add16", {"phi0"}},
    {"icmp17", {"add16", "br18"}},
    {"br18", {"icmp17"}},
    {"call1", {"br18"}},
    {"load2", {"br18"}},
    {"load7", {"br18"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load8", {"load7"}},
    {"getelementptr11", {"load7", "phi0"}},
    {"load4", {"getelementptr3"}},
    {"load9", {"load8"}},
    {"load12", {"getelementptr11"}},
    {"load5", {"load4"}},
    {"load13", {"load12"}},
    {"mul6", {"load5"}},
    {"mul10", {"mul6", "load9"}},
    {"add14", {"load13", "mul10"}},
    {"store15", {"add14", "load12"}},
    }},



    {"syr2k",{{"phi0", {"add23", "br25"}},
    {"add23", {"phi0"}},
    {"icmp24", {"add23", "br25"}},
    {"br25", {"icmp24"}},
    {"call1", {"br25"}},
    {"load2", {"br25"}},
    {"load7", {"br25"}},
    {"load12", {"br25"}},
    {"load3", {"load2"}},
    {"load8", {"load7"}},
    {"load13", {"load12"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load14", {"load13"}},
    {"load5", {"getelementptr4"}},
    {"load10", {"getelementptr9"}},
    {"load17", {"getelementptr9"}},
    {"load19", {"getelementptr4"}},
    {"shl6", {"load5"}},
    {"shl18", {"load17"}},
    {"mul11", {"shl6", "load10"}},
    {"mul20", {"shl18", "load19"}},
    {"add15", {"load14", "mul11"}},
    {"store16", {"add15", "load13"}},
    {"add21", {"mul20", "add15"}},
    {"store22", {"add21", "load13"}},
    }},



    {"atax_u",{{"phi0", {"add14", "br24"}},
    {"add14", {"phi0"}},
    {"icmp23", {"add14", "br24"}},
    {"br24", {"icmp23"}},
    {"call1", {"br24"}},
    {"load2", {"br24"}},
    {"load5", {"br24"}},
    {"load9", {"br24"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load6", {"load5"}},
    {"load10", {"load9"}},
    {"getelementptr15", {"load2", "add14"}},
    {"load19", {"load9"}},
    {"load4", {"getelementptr3"}},
    {"getelementptr7", {"load6", "phi0"}},
    {"load16", {"getelementptr15"}},
    {"getelementptr17", {"load6", "add14"}},
    {"load8", {"getelementptr7"}},
    {"load18", {"getelementptr17"}},
    {"mul11", {"load10", "load8"}},
    {"mul20", {"load19", "load18"}},
    {"add12", {"mul11", "load4"}},
    {"add21", {"mul20", "load16"}},
    {"store13", {"add12", "getelementptr3"}},
    {"store22", {"add21", "getelementptr15"}},
    }},



    {"cholesky_u",{{"phi0", {"add9", "br17"}},
    {"add9", {"phi0"}},
    {"icmp16", {"add9", "br17"}},
    {"br17", {"icmp16"}},
    {"call2", {"br17"}},
    {"load3", {"br17"}},
    {"load4", {"load3"}},
    {"getelementptr5", {"load4", "phi0"}},
    {"getelementptr10", {"load4", "add9"}},
    {"load6", {"getelementptr5"}},
    {"load7", {"getelementptr5"}},
    {"load11", {"getelementptr10"}},
    {"load12", {"getelementptr10"}},
    {"mul8", {"load7", "load6"}},
    {"mul13", {"load12", "load11"}},
    {"add14", {"mul13", "mul8"}},
    {"sub15", {"phi1", "add14"}},
    {"phi1", {"sub15", "br17"}},
    }},



    {"doitgen_u",{{"phi0", {"add19", "br29"}},
    {"add19", {"phi0"}},
    {"icmp28", {"add19", "br29"}},
    {"br29", {"icmp28"}},
    {"call1", {"br29"}},
    {"load2", {"br29"}},
    {"load6", {"br29"}},
    {"load11", {"br29"}},
    {"load3", {"load2"}},
    {"load7", {"load6"}},
    {"getelementptr12", {"load11", "phi0"}},
    {"getelementptr22", {"load11", "add19"}},
    {"load4", {"load3"}},
    {"load8", {"load7"}},
    {"load13", {"getelementptr12"}},
    {"load23", {"getelementptr22"}},
    {"load5", {"load4"}},
    {"getelementptr9", {"load8", "phi0"}},
    {"load14", {"load13"}},
    {"load18", {"load4"}},
    {"getelementptr20", {"load8", "add19"}},
    {"load24", {"load23"}},
    {"load10", {"getelementptr9"}},
    {"load21", {"getelementptr20"}},
    {"mul15", {"load14", "load10"}},
    {"mul25", {"load24", "load21"}},
    {"add16", {"mul15", "load5"}},
    {"add26", {"mul25", "load18"}},
    {"store17", {"add16", "load4"}},
    {"store27", {"add26", "load4"}},
    }},



    {"gemm_u",{{"phi0", {"add17", "br29"}},
    {"add17", {"phi0"}},
    {"icmp28", {"add17", "br29"}},
    {"br29", {"icmp28"}},
    {"call1", {"br29"}},
    {"load2", {"br29"}},
    {"load7", {"br29"}},
    {"load12", {"br29"}},
    {"load3", {"load2"}},
    {"getelementptr8", {"load7", "phi0"}},
    {"load13", {"load12"}},
    {"getelementptr21", {"load7", "add17"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load9", {"getelementptr8"}},
    {"load14", {"load13"}},
    {"getelementptr18", {"load3", "add17"}},
    {"load22", {"getelementptr21"}},
    {"load25", {"load13"}},
    {"load5", {"getelementptr4"}},
    {"load10", {"load9"}},
    {"load19", {"getelementptr18"}},
    {"load23", {"load22"}},
    {"mul6", {"load5"}},
    {"mul20", {"load19"}},
    {"mul11", {"mul6", "load10"}},
    {"mul24", {"mul20", "load23"}},
    {"add15", {"load14", "mul11"}},
    {"add26", {"load25", "mul24"}},
    {"store16", {"add15", "load13"}},
    {"store27", {"add26", "load13"}},
    }},



    {"symm_u",{{"phi0", {"add16", "br28"}},
    {"add16", {"phi0"}},
    {"icmp27", {"add16", "br28"}},
    {"br28", {"icmp27"}},
    {"call1", {"br28"}},
    {"load2", {"br28"}},
    {"load6", {"br28"}},
    {"load10", {"br28"}},
    {"getelementptr3", {"load2", "phi0"}},
    {"load7", {"load6"}},
    {"getelementptr11", {"load10", "phi0"}},
    {"getelementptr17", {"load2", "add16"}},
    {"getelementptr22", {"load10", "add16"}},
    {"load4", {"getelementptr3"}},
    {"load8", {"load7"}},
    {"load12", {"getelementptr11"}},
    {"load18", {"getelementptr17"}},
    {"load20", {"load7"}},
    {"load23", {"getelementptr22"}},
    {"load5", {"load4"}},
    {"load13", {"load12"}},
    {"load19", {"load18"}},
    {"load24", {"load23"}},
    {"mul9", {"load8", "load5"}},
    {"mul21", {"load20", "load19"}},
    {"add14", {"load13", "mul9"}},
    {"add25", {"load24", "mul21"}},
    {"store15", {"add14", "load12"}},
    {"store26", {"add25", "load23"}},
    }},



    {"syrk_u",{{"phi0", {"add13", "br21"}},
    {"add13", {"phi0"}},
    {"icmp20", {"add13", "br21"}},
    {"br21", {"icmp20"}},
    {"call1", {"br21"}},
    {"load2", {"br21"}},
    {"load8", {"br21"}},
    {"load3", {"load2"}},
    {"load9", {"load8"}},
    {"getelementptr4", {"load3", "phi0"}},
    {"load10", {"load9"}},
    {"getelementptr14", {"load3", "add13"}},
    {"load5", {"getelementptr4"}},
    {"load15", {"getelementptr14"}},
    {"mul6", {"load5"}},
    {"mul16", {"load15"}},
    {"mul7", {"mul6", "load5"}},
    {"mul17", {"mul16", "load15"}},
    {"add11", {"load10", "mul7"}},
    {"store12", {"add11", "load9"}},
    {"add18", {"mul17", "add11"}},
    {"store19", {"add18", "load9"}},
    }},

};

static map<string, map<string, vector<string>>> dependency_successors_kernels = {
    {"atax",{{"phi0", {"getelementptr3", "getelementptr7", "add14"}},
    {"add14", {"phi0", "icmp15"}},
    {"icmp15", {"br16"}},
    {"br16", {"phi0", "call1", "load2", "load5", "load9", "icmp15"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3"}},
    {"load5", {"load6"}},
    {"load9", {"load10"}},
    {"getelementptr3", {"load4", "store13"}},
    {"load6", {"getelementptr7"}},
    {"load10", {"mul11"}},
    {"load4", {"add12"}},
    {"getelementptr7", {"load8"}},
    {"load8", {"mul11"}},
    {"mul11", {"add12"}},
    {"add12", {"store13"}},
    {"store13", {"N/A"}},
    }},



    {"cholesky",{{"phi0", {"getelementptr5", "add10"}},
    {"add10", {"phi0", "icmp11"}},
    {"icmp11", {"br12"}},
    {"br12", {"phi0", "phi1", "call2", "load3", "icmp11"}},
    {"call2", {"N/A"}},
    {"load3", {"load4"}},
    {"load4", {"getelementptr5"}},
    {"getelementptr5", {"load6", "load7"}},
    {"load6", {"mul8"}},
    {"load7", {"mul8"}},
    {"mul8", {"sub9"}},
    {"sub9", {"phi1"}},
    {"phi1", {"sub9"}},
    }},



    {"doitgen",{{"phi0", {"getelementptr9", "getelementptr12", "add18"}},
    {"add18", {"phi0", "icmp19"}},
    {"icmp19", {"br20"}},
    {"br20", {"phi0", "call1", "load2", "load6", "load11", "icmp19"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load6", {"load7"}},
    {"load11", {"getelementptr12"}},
    {"load3", {"load4"}},
    {"load7", {"load8"}},
    {"getelementptr12", {"load13"}},
    {"load4", {"load5", "store17"}},
    {"load8", {"getelementptr9"}},
    {"load13", {"load14"}},
    {"load5", {"add16"}},
    {"getelementptr9", {"load10"}},
    {"load14", {"mul15"}},
    {"load10", {"mul15"}},
    {"mul15", {"add16"}},
    {"add16", {"store17"}},
    {"store17", {"N/A"}},
    }},



    {"bicg",{{"phi0", {"getelementptr3", "getelementptr9", "getelementptr18", "add23"}},
    {"add23", {"phi0", "icmp24"}},
    {"icmp24", {"br25"}},
    {"br25", {"phi0", "call1", "load2", "load5", "load7", "load14", "load17", "icmp24"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3"}},
    {"load5", {"load6"}},
    {"load7", {"load8"}},
    {"load14", {"load15", "store22"}},
    {"load17", {"getelementptr18"}},
    {"getelementptr3", {"load4", "store13"}},
    {"load6", {"mul11"}},
    {"load8", {"getelementptr9"}},
    {"load15", {"add21"}},
    {"getelementptr18", {"load19"}},
    {"load4", {"add12"}},
    {"getelementptr9", {"load10", "load16"}},
    {"load19", {"mul20"}},
    {"load10", {"mul11"}},
    {"load16", {"mul20"}},
    {"mul11", {"add12"}},
    {"mul20", {"add21"}},
    {"add12", {"store13"}},
    {"add21", {"store22"}},
    {"store13", {"N/A"}},
    {"store22", {"N/A"}},
    }},



    {"gemm",{{"phi0", {"getelementptr4", "getelementptr8", "add17"}},
    {"add17", {"phi0", "icmp18"}},
    {"icmp18", {"br19"}},
    {"br19", {"phi0", "call1", "load2", "load7", "load12", "icmp18"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load7", {"getelementptr8"}},
    {"load12", {"load13"}},
    {"load3", {"getelementptr4"}},
    {"getelementptr8", {"load9"}},
    {"load13", {"load14", "store16"}},
    {"getelementptr4", {"load5"}},
    {"load9", {"load10"}},
    {"load14", {"add15"}},
    {"load5", {"mul6"}},
    {"load10", {"mul11"}},
    {"mul6", {"mul11"}},
    {"mul11", {"add15"}},
    {"add15", {"store16"}},
    {"store16", {"N/A"}},
    }},



    {"gemver",{{"phi0", {"getelementptr4", "getelementptr9", "getelementptr16", "add21"}},
    {"add21", {"phi0", "icmp22"}},
    {"icmp22", {"br23"}},
    {"br23", {"phi0", "call1", "load2", "load6", "load8", "load13", "load15", "icmp22"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load6", {"load7"}},
    {"load8", {"getelementptr9"}},
    {"load13", {"load14"}},
    {"load15", {"getelementptr16"}},
    {"load3", {"getelementptr4"}},
    {"load7", {"mul11"}},
    {"getelementptr9", {"load10"}},
    {"load14", {"mul18"}},
    {"getelementptr16", {"load17"}},
    {"getelementptr4", {"load5", "store20"}},
    {"load10", {"mul11"}},
    {"load17", {"mul18"}},
    {"load5", {"add12"}},
    {"mul11", {"add12"}},
    {"mul18", {"add19"}},
    {"add12", {"add19"}},
    {"add19", {"store20"}},
    {"store20", {"N/A"}},
    }},



    {"gesummv",{{"phi0", {"getelementptr4", "getelementptr7", "getelementptr16", "add24"}},
    {"add24", {"phi0", "icmp25"}},
    {"icmp25", {"br26"}},
    {"br26", {"phi0", "call1", "load2", "load6", "load10", "load14", "load20", "icmp25"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load6", {"getelementptr7"}},
    {"load10", {"load11", "store13"}},
    {"load14", {"load15"}},
    {"load20", {"load21", "store23"}},
    {"load3", {"getelementptr4"}},
    {"getelementptr7", {"load8", "load18"}},
    {"load11", {"add12"}},
    {"load15", {"getelementptr16"}},
    {"load21", {"add22"}},
    {"getelementptr4", {"load5"}},
    {"load8", {"mul9"}},
    {"getelementptr16", {"load17"}},
    {"load18", {"mul19"}},
    {"load5", {"mul9"}},
    {"load17", {"mul19"}},
    {"mul9", {"add12"}},
    {"mul19", {"add22"}},
    {"add12", {"store13"}},
    {"add22", {"store23"}},
    {"store13", {"N/A"}},
    {"store23", {"N/A"}},
    }},



    {"mvt",{{"phi0", {"getelementptr5", "getelementptr9", "add14"}},
    {"add14", {"phi0", "icmp15"}},
    {"icmp15", {"br16"}},
    {"br16", {"phi0", "call1", "load2", "load4", "load8", "icmp15"}},
    {"call1", {"N/A"}},
    {"load2", {"load3", "store13"}},
    {"load4", {"getelementptr5"}},
    {"load8", {"getelementptr9"}},
    {"load3", {"add12"}},
    {"getelementptr5", {"load6"}},
    {"getelementptr9", {"load10"}},
    {"load6", {"load7"}},
    {"load10", {"mul11"}},
    {"load7", {"mul11"}},
    {"mul11", {"add12"}},
    {"add12", {"store13"}},
    {"store13", {"N/A"}},
    }},



    {"symm",{{"phi0", {"getelementptr3", "getelementptr11", "add16"}},
    {"add16", {"phi0", "icmp17"}},
    {"icmp17", {"br18"}},
    {"br18", {"phi0", "call1", "load2", "load6", "load10", "icmp17"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3"}},
    {"load6", {"load7"}},
    {"load10", {"getelementptr11"}},
    {"getelementptr3", {"load4"}},
    {"load7", {"load8"}},
    {"getelementptr11", {"load12"}},
    {"load4", {"load5"}},
    {"load8", {"mul9"}},
    {"load12", {"load13", "store15"}},
    {"load5", {"mul9"}},
    {"load13", {"add14"}},
    {"mul9", {"add14"}},
    {"add14", {"store15"}},
    {"store15", {"N/A"}},
    }},



    {"syrk",{{"phi0", {"getelementptr4", "add13"}},
    {"add13", {"phi0", "icmp14"}},
    {"icmp14", {"br15"}},
    {"br15", {"phi0", "call1", "load2", "load8", "icmp14"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load8", {"load9"}},
    {"load3", {"getelementptr4"}},
    {"load9", {"load10", "store12"}},
    {"getelementptr4", {"load5"}},
    {"load10", {"add11"}},
    {"load5", {"mul6", "mul7"}},
    {"mul6", {"mul7"}},
    {"mul7", {"add11"}},
    {"add11", {"store12"}},
    {"store12", {"N/A"}},
    }},



    {"trmm",{{"phi0", {"getelementptr3", "getelementptr11", "add16"}},
    {"add16", {"phi0", "icmp17"}},
    {"icmp17", {"br18"}},
    {"br18", {"phi0", "call1", "load2", "load7", "icmp17"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3"}},
    {"load7", {"load8", "getelementptr11"}},
    {"getelementptr3", {"load4"}},
    {"load8", {"load9"}},
    {"getelementptr11", {"load12"}},
    {"load4", {"load5"}},
    {"load9", {"mul10"}},
    {"load12", {"load13", "store15"}},
    {"load5", {"mul6"}},
    {"load13", {"add14"}},
    {"mul6", {"mul10"}},
    {"mul10", {"add14"}},
    {"add14", {"store15"}},
    {"store15", {"N/A"}},
    }},



    {"syr2k",{{"phi0", {"getelementptr4", "getelementptr9", "add23"}},
    {"add23", {"phi0", "icmp24"}},
    {"icmp24", {"br25"}},
    {"br25", {"phi0", "call1", "load2", "load7", "load12", "icmp24"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load7", {"load8"}},
    {"load12", {"load13"}},
    {"load3", {"getelementptr4"}},
    {"load8", {"getelementptr9"}},
    {"load13", {"load14", "store16", "store22"}},
    {"getelementptr4", {"load5", "load19"}},
    {"getelementptr9", {"load10", "load17"}},
    {"load14", {"add15"}},
    {"load5", {"shl6"}},
    {"load10", {"mul11"}},
    {"load17", {"shl18"}},
    {"load19", {"mul20"}},
    {"shl6", {"mul11"}},
    {"shl18", {"mul20"}},
    {"mul11", {"add15"}},
    {"mul20", {"add21"}},
    {"add15", {"store16", "add21"}},
    {"store16", {"N/A"}},
    {"add21", {"store22"}},
    {"store22", {"N/A"}},
    }},



    {"atax_u",{{"phi0", {"getelementptr3", "getelementptr7", "add14"}},
    {"add14", {"phi0", "getelementptr15", "getelementptr17", "icmp23"}},
    {"icmp23", {"br24"}},
    {"br24", {"phi0", "call1", "load2", "load5", "load9", "icmp23"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3", "getelementptr15"}},
    {"load5", {"load6"}},
    {"load9", {"load10", "load19"}},
    {"getelementptr3", {"load4", "store13"}},
    {"load6", {"getelementptr7", "getelementptr17"}},
    {"load10", {"mul11"}},
    {"getelementptr15", {"load16", "store22"}},
    {"load19", {"mul20"}},
    {"load4", {"add12"}},
    {"getelementptr7", {"load8"}},
    {"load16", {"add21"}},
    {"getelementptr17", {"load18"}},
    {"load8", {"mul11"}},
    {"load18", {"mul20"}},
    {"mul11", {"add12"}},
    {"mul20", {"add21"}},
    {"add12", {"store13"}},
    {"add21", {"store22"}},
    {"store13", {"N/A"}},
    {"store22", {"N/A"}},
    }},



    {"cholesky_u",{{"phi0", {"getelementptr5", "add9"}},
    {"add9", {"phi0", "getelementptr10", "icmp16"}},
    {"icmp16", {"br17"}},
    {"br17", {"phi0", "phi1", "call2", "load3", "icmp16"}},
    {"call2", {"N/A"}},
    {"load3", {"load4"}},
    {"load4", {"getelementptr5", "getelementptr10"}},
    {"getelementptr5", {"load6", "load7"}},
    {"getelementptr10", {"load11", "load12"}},
    {"load6", {"mul8"}},
    {"load7", {"mul8"}},
    {"load11", {"mul13"}},
    {"load12", {"mul13"}},
    {"mul8", {"add14"}},
    {"mul13", {"add14"}},
    {"add14", {"sub15"}},
    {"sub15", {"phi1"}},
    {"phi1", {"sub15"}},
    }},



    {"doitgen_u",{{"phi0", {"getelementptr9", "getelementptr12", "add19"}},
    {"add19", {"phi0", "getelementptr20", "getelementptr22", "icmp28"}},
    {"icmp28", {"br29"}},
    {"br29", {"phi0", "call1", "load2", "load6", "load11", "icmp28"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load6", {"load7"}},
    {"load11", {"getelementptr12", "getelementptr22"}},
    {"load3", {"load4"}},
    {"load7", {"load8"}},
    {"getelementptr12", {"load13"}},
    {"getelementptr22", {"load23"}},
    {"load4", {"load5", "store17", "load18", "store27"}},
    {"load8", {"getelementptr9", "getelementptr20"}},
    {"load13", {"load14"}},
    {"load23", {"load24"}},
    {"load5", {"add16"}},
    {"getelementptr9", {"load10"}},
    {"load14", {"mul15"}},
    {"load18", {"add26"}},
    {"getelementptr20", {"load21"}},
    {"load24", {"mul25"}},
    {"load10", {"mul15"}},
    {"load21", {"mul25"}},
    {"mul15", {"add16"}},
    {"mul25", {"add26"}},
    {"add16", {"store17"}},
    {"add26", {"store27"}},
    {"store17", {"N/A"}},
    {"store27", {"N/A"}},
    }},



    {"gemm_u",{{"phi0", {"getelementptr4", "getelementptr8", "add17"}},
    {"add17", {"phi0", "getelementptr18", "getelementptr21", "icmp28"}},
    {"icmp28", {"br29"}},
    {"br29", {"phi0", "call1", "load2", "load7", "load12", "icmp28"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load7", {"getelementptr8", "getelementptr21"}},
    {"load12", {"load13"}},
    {"load3", {"getelementptr4", "getelementptr18"}},
    {"getelementptr8", {"load9"}},
    {"load13", {"load14", "store16", "load25", "store27"}},
    {"getelementptr21", {"load22"}},
    {"getelementptr4", {"load5"}},
    {"load9", {"load10"}},
    {"load14", {"add15"}},
    {"getelementptr18", {"load19"}},
    {"load22", {"load23"}},
    {"load25", {"add26"}},
    {"load5", {"mul6"}},
    {"load10", {"mul11"}},
    {"load19", {"mul20"}},
    {"load23", {"mul24"}},
    {"mul6", {"mul11"}},
    {"mul20", {"mul24"}},
    {"mul11", {"add15"}},
    {"mul24", {"add26"}},
    {"add15", {"store16"}},
    {"add26", {"store27"}},
    {"store16", {"N/A"}},
    {"store27", {"N/A"}},
    }},



    {"symm_u",{{"phi0", {"getelementptr3", "getelementptr11", "add16"}},
    {"add16", {"phi0", "getelementptr17", "getelementptr22", "icmp27"}},
    {"icmp27", {"br28"}},
    {"br28", {"phi0", "call1", "load2", "load6", "load10", "icmp27"}},
    {"call1", {"N/A"}},
    {"load2", {"getelementptr3", "getelementptr17"}},
    {"load6", {"load7"}},
    {"load10", {"getelementptr11", "getelementptr22"}},
    {"getelementptr3", {"load4"}},
    {"load7", {"load8", "load20"}},
    {"getelementptr11", {"load12"}},
    {"getelementptr17", {"load18"}},
    {"getelementptr22", {"load23"}},
    {"load4", {"load5"}},
    {"load8", {"mul9"}},
    {"load12", {"load13", "store15"}},
    {"load18", {"load19"}},
    {"load20", {"mul21"}},
    {"load23", {"load24", "store26"}},
    {"load5", {"mul9"}},
    {"load13", {"add14"}},
    {"load19", {"mul21"}},
    {"load24", {"add25"}},
    {"mul9", {"add14"}},
    {"mul21", {"add25"}},
    {"add14", {"store15"}},
    {"add25", {"store26"}},
    {"store15", {"N/A"}},
    {"store26", {"N/A"}},
    }},



    {"syrk_u",{{"phi0", {"getelementptr4", "add13"}},
    {"add13", {"phi0", "getelementptr14", "icmp20"}},
    {"icmp20", {"br21"}},
    {"br21", {"phi0", "call1", "load2", "load8", "icmp20"}},
    {"call1", {"N/A"}},
    {"load2", {"load3"}},
    {"load8", {"load9"}},
    {"load3", {"getelementptr4", "getelementptr14"}},
    {"load9", {"load10", "store12", "store19"}},
    {"getelementptr4", {"load5"}},
    {"load10", {"add11"}},
    {"getelementptr14", {"load15"}},
    {"load5", {"mul6", "mul7"}},
    {"load15", {"mul16", "mul17"}},
    {"mul6", {"mul7"}},
    {"mul16", {"mul17"}},
    {"mul7", {"add11"}},
    {"mul17", {"add18"}},
    {"add11", {"store12", "add18"}},
    {"store12", {"N/A"}},
    {"add18", {"store19"}},
    {"store19", {"N/A"}},
    }},

};