set SynModuleInfo {
  {SRCNAME Reset_Pipeline_VITIS_LOOP_685_5_VITIS_LOOP_686_6_VITIS_LOOP_687_7 MODELNAME Reset_Pipeline_VITIS_LOOP_685_5_VITIS_LOOP_686_6_VITIS_LOOP_687_7 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_685_5_VITIS_LOOP_686_6_VITIS_LOOP_687_7
    SUBMODULES {
      {MODELNAME runOne_mac_muladd_3ns_7ns_7ns_9_4_1 RTLNAME runOne_mac_muladd_3ns_7ns_7ns_9_4_1 BINDTYPE op TYPE add IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME runOne_flow_control_loop_pipe_sequential_init RTLNAME runOne_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME runOne_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME Reset_Pipeline_VITIS_LOOP_692_8_VITIS_LOOP_693_9 MODELNAME Reset_Pipeline_VITIS_LOOP_692_8_VITIS_LOOP_693_9 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_692_8_VITIS_LOOP_693_9}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_697_10_VITIS_LOOP_698_11_VITIS_LOOP_699_12 MODELNAME Reset_Pipeline_VITIS_LOOP_697_10_VITIS_LOOP_698_11_VITIS_LOOP_699_12 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_697_10_VITIS_LOOP_698_11_VITIS_LOOP_699_12}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_704_13 MODELNAME Reset_Pipeline_VITIS_LOOP_704_13 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_704_13
    SUBMODULES {
      {MODELNAME runOne_Reset_Pipeline_VITIS_LOOP_704_13_placement_static_kernels_values_ROM_AUTO_1R RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_704_13_placement_static_kernels_values_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Reset_Pipeline_VITIS_LOOP_707_14 MODELNAME Reset_Pipeline_VITIS_LOOP_707_14 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_707_14}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_710_15 MODELNAME Reset_Pipeline_VITIS_LOOP_710_15 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_710_15}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_713_16 MODELNAME Reset_Pipeline_VITIS_LOOP_713_16 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_713_16}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_716_17 MODELNAME Reset_Pipeline_VITIS_LOOP_716_17 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_716_17}
  {SRCNAME Reset_Pipeline_VITIS_LOOP_722_19_VITIS_LOOP_724_20 MODELNAME Reset_Pipeline_VITIS_LOOP_722_19_VITIS_LOOP_724_20 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_722_19_VITIS_LOOP_724_20
    SUBMODULES {
      {MODELNAME runOne_Reset_Pipeline_VITIS_LOOP_722_19_VITIS_LOOP_724_20_dependency_predecessors_kebkb RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_722_19_VITIS_LOOP_724_20_dependency_predecessors_kebkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Reset_Pipeline_VITIS_LOOP_734_21_VITIS_LOOP_736_22 MODELNAME Reset_Pipeline_VITIS_LOOP_734_21_VITIS_LOOP_736_22 RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_734_21_VITIS_LOOP_736_22
    SUBMODULES {
      {MODELNAME runOne_Reset_Pipeline_VITIS_LOOP_734_21_VITIS_LOOP_736_22_dependency_successors_kerncud RTLNAME runOne_Reset_Pipeline_VITIS_LOOP_734_21_VITIS_LOOP_736_22_dependency_successors_kerncud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Reset MODELNAME Reset RTLNAME runOne_Reset
    SUBMODULES {
      {MODELNAME runOne_mul_3ns_8ns_10_1_1 RTLNAME runOne_mul_3ns_8ns_10_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_601_2 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_601_2 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_601_2}
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_611_4 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_611_4 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_611_4}
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_618_5 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_618_5 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_618_5}
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_624_6 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_624_6 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_624_6}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4
    SUBMODULES {
      {MODELNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4_allocaeOg RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4_allocaeOg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_497_8_VITIS_LOOP_498_9 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_497_8_VITIS_LOOP_498_9 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_497_8_VITIS_LOOP_498_9}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_562_14 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_562_14 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_562_14}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_577_16 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_577_16 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_577_16}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_508_10 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_508_10 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_508_10}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_518_12 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_518_12 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_518_12}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_470_5 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_470_5 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_470_5}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_480_7 MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_480_7 RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_480_7}
  {SRCNAME CurOptPotentialPlacement_List_BypassLess_Gen MODELNAME CurOptPotentialPlacement_List_BypassLess_Gen RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen
    SUBMODULES {
      {MODELNAME runOne_mul_7ns_8ns_15_1_1 RTLNAME runOne_mul_7ns_8ns_15_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CGRA_NumTiles_shapes_values_ROM_g8j RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CGRA_NumTiles_shapes_values_ROM_g8j BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CurOptPotentialPlacement_List_Byhbi RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CurOptPotentialPlacement_List_Byhbi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_potentialPlacement_AllPreds_RAM_jbC RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_potentialPlacement_AllPreds_RAM_jbC BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_intersection_RAM_AUTO_1R1W RTLNAME runOne_CurOptPotentialPlacement_List_BypassLess_Gen_intersection_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_377_1 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_377_1 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_377_1
    SUBMODULES {
      {MODELNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_377_1_placement_static_Tile2LevkbM RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_377_1_placement_static_Tile2LevkbM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_388_2 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_388_2 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_388_2}
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_398_3 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_398_3 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_398_3}
  {SRCNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_415_5 MODELNAME dynamic_placement_routing_Pipeline_VITIS_LOOP_415_5 RTLNAME runOne_dynamic_placement_routing_Pipeline_VITIS_LOOP_415_5}
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_14_1 MODELNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_14_1 RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_14_1}
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_32_1 MODELNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_32_1 RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_32_1}
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_39_2 MODELNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_39_2 RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_39_2}
  {SRCNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1 MODELNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1 RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1}
  {SRCNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3 MODELNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3 RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3
    SUBMODULES {
      {MODELNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_bpsSlbW RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_bpsSlbW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_bpsSmb6 RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_bpsSmb6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_xy2Tncg RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_xy2Tncg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4 MODELNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4 RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4
    SUBMODULES {
      {MODELNAME runOne_srem_8ns_8ns_8_12_1 RTLNAME runOne_srem_8ns_8ns_8_12_1 BINDTYPE op TYPE srem IMPL auto LATENCY 11 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5 MODELNAME BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5 RTLNAME runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5}
  {SRCNAME BypassOptPlacement_Gen_Record MODELNAME BypassOptPlacement_Gen_Record RTLNAME runOne_BypassOptPlacement_Gen_Record
    SUBMODULES {
      {MODELNAME runOne_BypassOptPlacement_Gen_Record_Tile2XY_0_ROM_AUTO_1R RTLNAME runOne_BypassOptPlacement_Gen_Record_Tile2XY_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_BypassOptPlacement_Gen_Record_Tile2XY_1_ROM_AUTO_1R RTLNAME runOne_BypassOptPlacement_Gen_Record_Tile2XY_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_53_1 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_53_1 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_53_1}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_61_2 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_61_2 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_61_2}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_69_3 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_69_3 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_69_3}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_75_4 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_75_4 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_75_4}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_83_5 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_83_5 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_83_5}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_94_6 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_94_6 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_94_6}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_102_7 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_102_7 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_102_7}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_108_8 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_108_8 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_108_8}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_116_9 MODELNAME Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_116_9 RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt_Pipeline_VITIS_LOOP_116_9}
  {SRCNAME Dependency_Update_BypassMode_SrcTgt MODELNAME Dependency_Update_BypassMode_SrcTgt RTLNAME runOne_Dependency_Update_BypassMode_SrcTgt}
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_127_1 MODELNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_127_1 RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_127_1}
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_354_4 MODELNAME RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_354_4 RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_Pipeline_VITIS_LOOP_354_4
    SUBMODULES {
      {MODELNAME runOne_srem_8ns_8ns_7_12_1 RTLNAME runOne_srem_8ns_8ns_7_12_1 BINDTYPE op TYPE srem IMPL auto LATENCY 11 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME RoutingAvailability_CheckPredecessor_and_Placement MODELNAME RoutingAvailability_CheckPredecessor_and_Placement RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement
    SUBMODULES {
      {MODELNAME runOne_srem_8ns_8ns_7_12_seq_1 RTLNAME runOne_srem_8ns_8ns_7_12_seq_1 BINDTYPE op TYPE srem IMPL auto_seq LATENCY 11 ALLOW_PRAGMA 1}
      {MODELNAME runOne_mac_muladd_3ns_7ns_8s_10_4_1 RTLNAME runOne_mac_muladd_3ns_7ns_8s_10_4_1 BINDTYPE op TYPE add IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_bypassPreds_RAM_AUTO_1R1W RTLNAME runOne_RoutingAvailability_CheckPredecessor_and_Placement_bypassPreds_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dynamic_placement_routing MODELNAME dynamic_placement_routing RTLNAME runOne_dynamic_placement_routing
    SUBMODULES {
      {MODELNAME runOne_dynamic_placement_routing_predOpt_idx_List_RAM_AUTO_1R1W RTLNAME runOne_dynamic_placement_routing_predOpt_idx_List_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dynamic_placement_routing_placement_static_Opt2Tile_kernels_values1_ROM_AUTO_1R RTLNAME runOne_dynamic_placement_routing_placement_static_Opt2Tile_kernels_values1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dynamic_placement_routing_placement_static_Tile2Level_values_ROM_AUTO_1R RTLNAME runOne_dynamic_placement_routing_placement_static_Tile2Level_values_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dynamic_placement_routing_allocated_tiles_Maxlevels_dynamic_shapes_values_ROMqcK RTLNAME runOne_dynamic_placement_routing_allocated_tiles_Maxlevels_dynamic_shapes_values_ROMqcK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dynamic_placement_routing_allocated_tiles_levelsValidLen_shapes_values_ROM_AUrcU RTLNAME runOne_dynamic_placement_routing_allocated_tiles_levelsValidLen_shapes_values_ROM_AUrcU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dynamic_placement_routing_allocated_tiles_levels_dynamic_shapes_values_ROM_AUsc4 RTLNAME runOne_dynamic_placement_routing_allocated_tiles_levels_dynamic_shapes_values_ROM_AUsc4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME runOne MODELNAME runOne RTLNAME runOne IS_TOP 1
    SUBMODULES {
      {MODELNAME runOne_ddiv_64ns_64ns_64_31_no_dsp_1 RTLNAME runOne_ddiv_64ns_64ns_64_31_no_dsp_1 BINDTYPE op TYPE ddiv IMPL fabric LATENCY 30 ALLOW_PRAGMA 1}
      {MODELNAME runOne_sitodp_32ns_64_5_no_dsp_1 RTLNAME runOne_sitodp_32ns_64_5_no_dsp_1 BINDTYPE op TYPE sitodp IMPL auto LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME runOne_mul_8s_10ns_18_1_1 RTLNAME runOne_mul_8s_10ns_18_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME runOne_srem_8s_5ns_8_12_seq_1 RTLNAME runOne_srem_8s_5ns_8_12_seq_1 BINDTYPE op TYPE srem IMPL auto_seq LATENCY 11 ALLOW_PRAGMA 1}
      {MODELNAME runOne_DFG_NodesCount_kernels_values_ROM_AUTO_1R RTLNAME runOne_DFG_NodesCount_kernels_values_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_mask_table_ROM_AUTO_1R RTLNAME runOne_mask_table_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_predecessors_RAM_AUTO_1R1W RTLNAME runOne_predecessors_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_dynamic_bypass_RAM_AUTO_1R1W RTLNAME runOne_placement_dynamic_bypass_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_dynamic_occupy_RAM_AUTO_1R1W RTLNAME runOne_placement_dynamic_occupy_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_dynamic_bypass_occupy_RAM_AUTO_1R1W RTLNAME runOne_placement_dynamic_bypass_occupy_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_dynamic_dict_Opt2PC_keys_RAM_AUTO_1R1W RTLNAME runOne_placement_dynamic_dict_Opt2PC_keys_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_dynamic_dict_Opt2Tile_values_RAM_AUTO_1R1W RTLNAME runOne_placement_dynamic_dict_Opt2Tile_values_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_placement_done_values_RAM_AUTO_1R1W RTLNAME runOne_placement_done_values_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dependency_predecessor_values_RAM_AUTO_1R1W RTLNAME runOne_dependency_predecessor_values_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_dependency_successor_values_RAM_AUTO_1R1W RTLNAME runOne_dependency_successor_values_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME runOne_curOptPotentialPlacement_RAM_AUTO_1R1W RTLNAME runOne_curOptPotentialPlacement_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
