-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity runOne_BypassOptPlacement_Gen_Record is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bypassOptIdx_i : IN STD_LOGIC_VECTOR (7 downto 0);
    bypassOptIdx_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    bypassOptIdx_o_ap_vld : OUT STD_LOGIC;
    bypassOpt : OUT STD_LOGIC_VECTOR (7 downto 0);
    bypassOpt_ap_vld : OUT STD_LOGIC;
    bypassSrcOpt : IN STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_dict_Opt2PC_keys_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    placement_dynamic_dict_Opt2PC_keys_ce0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2PC_keys_we0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2PC_keys_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_dict_Opt2PC_keys_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_dict_Opt2PC_values_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    placement_dynamic_dict_Opt2PC_values_ce0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2PC_values_we0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2PC_values_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_dict_Opt2PC_values_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    IDX_pd_bypass_i : IN STD_LOGIC_VECTOR (7 downto 0);
    IDX_pd_bypass_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    IDX_pd_bypass_o_ap_vld : OUT STD_LOGIC;
    DynamicPlacement_II : IN STD_LOGIC_VECTOR (7 downto 0);
    bypassSrcTile : IN STD_LOGIC_VECTOR (4 downto 0);
    bypassTgtTile : IN STD_LOGIC_VECTOR (3 downto 0);
    shape_idx : IN STD_LOGIC_VECTOR (4 downto 0);
    idx_pd_i : IN STD_LOGIC_VECTOR (3 downto 0);
    idx_pd_o : OUT STD_LOGIC_VECTOR (3 downto 0);
    idx_pd_o_ap_vld : OUT STD_LOGIC;
    placement_dynamic_bypass_occupy_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    placement_dynamic_bypass_occupy_ce0 : OUT STD_LOGIC;
    placement_dynamic_bypass_occupy_we0 : OUT STD_LOGIC;
    placement_dynamic_bypass_occupy_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    placement_dynamic_bypass_occupy_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    placement_dynamic_bypass_occupy_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    placement_dynamic_bypass_occupy_ce1 : OUT STD_LOGIC;
    placement_dynamic_bypass_occupy_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
    placement_dynamic_bypass_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    placement_dynamic_bypass_ce0 : OUT STD_LOGIC;
    placement_dynamic_bypass_we0 : OUT STD_LOGIC;
    placement_dynamic_bypass_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_bypass_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    bypassOpt_wrAddr_i : IN STD_LOGIC_VECTOR (7 downto 0);
    bypassOpt_wrAddr_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    bypassOpt_wrAddr_o_ap_vld : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2Tile_keys_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    placement_dynamic_dict_Opt2Tile_keys_ce0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2Tile_keys_we0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2Tile_keys_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    placement_dynamic_dict_Opt2Tile_values_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    placement_dynamic_dict_Opt2Tile_values_ce0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2Tile_values_we0 : OUT STD_LOGIC;
    placement_dynamic_dict_Opt2Tile_values_d0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    placement_done_values_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    placement_done_values_ce0 : OUT STD_LOGIC;
    placement_done_values_we0 : OUT STD_LOGIC;
    placement_done_values_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of runOne_BypassOptPlacement_Gen_Record is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Tile2XY_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile2XY_0_ce0 : STD_LOGIC;
    signal Tile2XY_0_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal Tile2XY_0_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile2XY_0_ce1 : STD_LOGIC;
    signal Tile2XY_0_q1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Tile2XY_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile2XY_1_ce0 : STD_LOGIC;
    signal Tile2XY_1_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal Tile2XY_1_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile2XY_1_ce1 : STD_LOGIC;
    signal Tile2XY_1_q1 : STD_LOGIC_VECTOR (1 downto 0);
    signal CGRA_NumTiles_shapes_values_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal CGRA_NumTiles_shapes_values_ce0 : STD_LOGIC;
    signal CGRA_NumTiles_shapes_values_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal allocated_tiles_shapes_values_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal allocated_tiles_shapes_values_ce0 : STD_LOGIC;
    signal allocated_tiles_shapes_values_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal Tile2XY_0_load_reg_996 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp28_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp28_reg_1001 : STD_LOGIC_VECTOR (0 downto 0);
    signal Tile2XY_1_load_reg_1006 : STD_LOGIC_VECTOR (1 downto 0);
    signal cmp77_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp77_reg_1011 : STD_LOGIC_VECTOR (0 downto 0);
    signal CGRA_NumTiles_shapes_values_load_reg_1016 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln205_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln205_reg_1021 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln218_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln218_reg_1026 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln192_fu_527_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln192_reg_1031 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock_reg_1036 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal bypassOptIdx_load_reg_1045 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln192_fu_564_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln192_reg_1052 : STD_LOGIC_VECTOR (7 downto 0);
    signal upperLimit_fu_580_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal upperLimit_reg_1060 : STD_LOGIC_VECTOR (7 downto 0);
    signal tileId_reg_1082 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln169_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_reg_1089 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_reg_1099 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_1_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_1_reg_1105 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_reg_1111 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_4_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_4_reg_1117 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_1123 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub173_fu_809_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub173_reg_1129 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sub182_fu_837_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub182_reg_1134 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal targetBlock15_reg_1139 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_71_reload_cast_fu_865_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_71_reload_cast_reg_1146 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_done : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_idle : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_ready : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_ce0 : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_done : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_idle : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_ready : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_idle : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_ready : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce0 : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce1 : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_idle : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_ready : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out_ap_vld : STD_LOGIC;
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_ce0 : STD_LOGIC;
    signal yDiff_210_reg_335 : STD_LOGIC_VECTOR (1 downto 0);
    signal xDiff_28_reg_344 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_retval_0_phi_fu_357_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_reg_353 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg : STD_LOGIC := '0';
    signal bypassSrcOptIdx_loc_fu_146 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg : STD_LOGIC := '0';
    signal yDiff_2_phi_loc_fu_142 : STD_LOGIC_VECTOR (1 downto 0);
    signal xDiff_2_phi_loc_fu_138 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_50_loc_fu_134 : STD_LOGIC_VECTOR (3 downto 0);
    signal xDiff_2_loc_fu_130 : STD_LOGIC_VECTOR (1 downto 0);
    signal yDiff_2_loc_fu_126 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg : STD_LOGIC := '0';
    signal p_loc_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln252_loc_fu_118 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_71_loc_fu_114 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_73_loc_fu_110 : STD_LOGIC_VECTOR (12 downto 0);
    signal idxprom20_fu_433_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom24_fu_443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln233_fu_453_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln192_fu_537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln243_fu_618_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln252_reload_cast_fu_857_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln262_fu_873_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_73_reload_cast_fu_897_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln186_fu_552_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_idx_pd_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln268_fu_882_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln205_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln218_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl_fu_519_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln192_1_fu_515_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_611_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_36_fu_631_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_623_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln149_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln148_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_2_fu_681_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln153_1_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln149_3_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dirInIdx_fu_719_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln244_fu_747_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln155_fu_733_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln149_1_fu_757_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln149_2_fu_764_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln149_3_fu_771_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln169_fu_726_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln149_fu_750_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln244_fu_740_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln149_4_fu_782_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln149_fu_778_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp29_op_cast_cast_fu_802_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp25_cast_op_fu_796_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln149_5_fu_789_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp42_op_fu_817_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp48_op_fu_830_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp44_op_fu_823_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bypassSrcOpt_load : IN STD_LOGIC_VECTOR (7 downto 0);
        bypassSrcOptIdx_out : OUT STD_LOGIC_VECTOR (6 downto 0);
        bypassSrcOptIdx_out_ap_vld : OUT STD_LOGIC;
        placement_dynamic_dict_Opt2PC_keys_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        placement_dynamic_dict_Opt2PC_keys_ce0 : OUT STD_LOGIC;
        placement_dynamic_dict_Opt2PC_keys_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Tile2XY_0_load : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp28 : IN STD_LOGIC_VECTOR (0 downto 0);
        and_ln205 : IN STD_LOGIC_VECTOR (0 downto 0);
        Tile2XY_1_load : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp77 : IN STD_LOGIC_VECTOR (0 downto 0);
        and_ln218 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub_ln192 : IN STD_LOGIC_VECTOR (5 downto 0);
        CGRA_NumTiles_shapes_values_load : IN STD_LOGIC_VECTOR (3 downto 0);
        shape_idx_load : IN STD_LOGIC_VECTOR (4 downto 0);
        yDiff_2_phi_out : OUT STD_LOGIC_VECTOR (1 downto 0);
        yDiff_2_phi_out_ap_vld : OUT STD_LOGIC;
        xDiff_2_phi_out : OUT STD_LOGIC_VECTOR (1 downto 0);
        xDiff_2_phi_out_ap_vld : OUT STD_LOGIC;
        i_50_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        i_50_out_ap_vld : OUT STD_LOGIC;
        xDiff_2_out : OUT STD_LOGIC_VECTOR (1 downto 0);
        xDiff_2_out_ap_vld : OUT STD_LOGIC;
        yDiff_2_out : OUT STD_LOGIC_VECTOR (1 downto 0);
        yDiff_2_out_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln192 : IN STD_LOGIC_VECTOR (7 downto 0);
        DynamicPlacement_II_load : IN STD_LOGIC_VECTOR (7 downto 0);
        tileId : IN STD_LOGIC_VECTOR (3 downto 0);
        idxprom174 : IN STD_LOGIC_VECTOR (3 downto 0);
        idxprom20 : IN STD_LOGIC_VECTOR (4 downto 0);
        sub182 : IN STD_LOGIC_VECTOR (3 downto 0);
        upperLimit : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        add_ln252_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        add_ln252_out_ap_vld : OUT STD_LOGIC;
        tmp_71_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        tmp_71_out_ap_vld : OUT STD_LOGIC;
        placement_dynamic_bypass_occupy_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        placement_dynamic_bypass_occupy_ce0 : OUT STD_LOGIC;
        placement_dynamic_bypass_occupy_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        placement_dynamic_bypass_occupy_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
        placement_dynamic_bypass_occupy_ce1 : OUT STD_LOGIC;
        placement_dynamic_bypass_occupy_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
        IDX_pd_bypass_i : IN STD_LOGIC_VECTOR (7 downto 0);
        IDX_pd_bypass_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        IDX_pd_bypass_o_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        idxprom190 : IN STD_LOGIC_VECTOR (7 downto 0);
        tileId : IN STD_LOGIC_VECTOR (3 downto 0);
        tmp_73_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        tmp_73_out_ap_vld : OUT STD_LOGIC;
        placement_dynamic_bypass_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        placement_dynamic_bypass_ce0 : OUT STD_LOGIC;
        placement_dynamic_bypass_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component runOne_BypassOptPlacement_Gen_Record_Tile2XY_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component runOne_BypassOptPlacement_Gen_Record_Tile2XY_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CGRA_NumTiles_shapes_values_ROM_g8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4_allocaeOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    Tile2XY_0_U : component runOne_BypassOptPlacement_Gen_Record_Tile2XY_0_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Tile2XY_0_address0,
        ce0 => Tile2XY_0_ce0,
        q0 => Tile2XY_0_q0,
        address1 => Tile2XY_0_address1,
        ce1 => Tile2XY_0_ce1,
        q1 => Tile2XY_0_q1);

    Tile2XY_1_U : component runOne_BypassOptPlacement_Gen_Record_Tile2XY_1_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Tile2XY_1_address0,
        ce0 => Tile2XY_1_ce0,
        q0 => Tile2XY_1_q0,
        address1 => Tile2XY_1_address1,
        ce1 => Tile2XY_1_ce1,
        q1 => Tile2XY_1_q1);

    CGRA_NumTiles_shapes_values_U : component runOne_CurOptPotentialPlacement_List_BypassLess_Gen_CGRA_NumTiles_shapes_values_ROM_g8j
    generic map (
        DataWidth => 4,
        AddressRange => 20,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => CGRA_NumTiles_shapes_values_address0,
        ce0 => CGRA_NumTiles_shapes_values_ce0,
        q0 => CGRA_NumTiles_shapes_values_q0);

    allocated_tiles_shapes_values_U : component runOne_CurOptPotentialPlacement_List_BypassLess_Gen_Pipeline_VITIS_LOOP_453_4_allocaeOg
    generic map (
        DataWidth => 4,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => allocated_tiles_shapes_values_address0,
        ce0 => allocated_tiles_shapes_values_ce0,
        q0 => allocated_tiles_shapes_values_q0);

    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365 : component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start,
        ap_done => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_done,
        ap_idle => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_idle,
        ap_ready => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_ready,
        bypassSrcOpt_load => bypassSrcOpt,
        bypassSrcOptIdx_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out,
        bypassSrcOptIdx_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out_ap_vld,
        placement_dynamic_dict_Opt2PC_keys_address0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_address0,
        placement_dynamic_dict_Opt2PC_keys_ce0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_ce0,
        placement_dynamic_dict_Opt2PC_keys_q0 => placement_dynamic_dict_Opt2PC_keys_q0);

    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373 : component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start,
        ap_done => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_done,
        ap_idle => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_idle,
        ap_ready => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_ready,
        Tile2XY_0_load => Tile2XY_0_load_reg_996,
        cmp28 => cmp28_reg_1001,
        and_ln205 => and_ln205_reg_1021,
        Tile2XY_1_load => Tile2XY_1_load_reg_1006,
        cmp77 => cmp77_reg_1011,
        and_ln218 => and_ln218_reg_1026,
        sub_ln192 => sub_ln192_reg_1031,
        CGRA_NumTiles_shapes_values_load => CGRA_NumTiles_shapes_values_load_reg_1016,
        shape_idx_load => shape_idx,
        yDiff_2_phi_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out,
        yDiff_2_phi_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out_ap_vld,
        xDiff_2_phi_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out,
        xDiff_2_phi_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out_ap_vld,
        i_50_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out,
        i_50_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out_ap_vld,
        xDiff_2_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out,
        xDiff_2_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out_ap_vld,
        yDiff_2_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out,
        yDiff_2_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out_ap_vld,
        ap_return => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_return);

    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402 : component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start,
        ap_done => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done,
        ap_idle => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_idle,
        ap_ready => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_ready,
        add_ln192 => add_ln192_reg_1052,
        DynamicPlacement_II_load => DynamicPlacement_II,
        tileId => tileId_reg_1082,
        idxprom174 => sub173_reg_1129,
        idxprom20 => bypassSrcTile,
        sub182 => sub182_reg_1134,
        upperLimit => upperLimit_reg_1060,
        p_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out,
        p_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out_ap_vld,
        add_ln252_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out,
        add_ln252_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out_ap_vld,
        tmp_71_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out,
        tmp_71_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out_ap_vld,
        placement_dynamic_bypass_occupy_address0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address0,
        placement_dynamic_bypass_occupy_ce0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce0,
        placement_dynamic_bypass_occupy_q0 => placement_dynamic_bypass_occupy_q0,
        placement_dynamic_bypass_occupy_address1 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address1,
        placement_dynamic_bypass_occupy_ce1 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce1,
        placement_dynamic_bypass_occupy_q1 => placement_dynamic_bypass_occupy_q1,
        IDX_pd_bypass_i => IDX_pd_bypass_i,
        IDX_pd_bypass_o => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o,
        IDX_pd_bypass_o_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld,
        ap_return => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_return);

    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420 : component runOne_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start,
        ap_done => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done,
        ap_idle => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_idle,
        ap_ready => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_ready,
        idxprom190 => p_loc_fu_122,
        tileId => tileId_reg_1082,
        tmp_73_out => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out,
        tmp_73_out_ap_vld => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out_ap_vld,
        placement_dynamic_bypass_address0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_address0,
        placement_dynamic_bypass_ce0 => grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_ce0,
        placement_dynamic_bypass_q0 => placement_dynamic_bypass_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_return_preg <= ap_phi_mux_retval_0_phi_fu_357_p4;
                end if; 
            end if;
        end if;
    end process;


    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_ready = ap_const_logic_1)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_ready = ap_const_logic_1)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_ready = ap_const_logic_1)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg <= ap_const_logic_0;
            else
                if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_ready = ap_const_logic_1)) then 
                    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    retval_0_reg_353_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((targetBlock15_reg_1139 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                retval_0_reg_353 <= ap_const_lv1_0;
            elsif (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                retval_0_reg_353 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    xDiff_28_reg_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                if ((targetBlock_reg_1036 = ap_const_lv1_1)) then 
                    xDiff_28_reg_344 <= xDiff_2_phi_loc_fu_138;
                elsif ((targetBlock_reg_1036 = ap_const_lv1_0)) then 
                    xDiff_28_reg_344 <= xDiff_2_loc_fu_130;
                end if;
            end if; 
        end if;
    end process;

    yDiff_210_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                if ((targetBlock_reg_1036 = ap_const_lv1_1)) then 
                    yDiff_210_reg_335 <= yDiff_2_phi_loc_fu_142;
                elsif ((targetBlock_reg_1036 = ap_const_lv1_0)) then 
                    yDiff_210_reg_335 <= yDiff_2_loc_fu_126;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                CGRA_NumTiles_shapes_values_load_reg_1016 <= CGRA_NumTiles_shapes_values_q0;
                Tile2XY_0_load_reg_996 <= Tile2XY_0_q1;
                Tile2XY_1_load_reg_1006 <= Tile2XY_1_q1;
                and_ln205_reg_1021 <= and_ln205_fu_495_p2;
                and_ln218_reg_1026 <= and_ln218_fu_508_p2;
                cmp28_reg_1001 <= cmp28_fu_463_p2;
                cmp77_reg_1011 <= cmp77_fu_470_p2;
                sub_ln192_reg_1031 <= sub_ln192_fu_527_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln192_reg_1052 <= add_ln192_fu_564_p2;
                bypassOptIdx_load_reg_1045 <= bypassOptIdx_i;
                upperLimit_reg_1060 <= upperLimit_fu_580_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                add_ln252_loc_fu_118 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_add_ln252_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                and_ln149_1_reg_1105 <= and_ln149_1_fu_675_p2;
                and_ln149_4_reg_1117 <= and_ln149_4_fu_707_p2;
                and_ln149_reg_1099 <= and_ln149_fu_657_p2;
                empty_reg_1123 <= empty_fu_713_p2;
                icmp_ln169_reg_1089 <= icmp_ln169_fu_639_p2;
                tileId_reg_1082 <= allocated_tiles_shapes_values_q0;
                tmp_37_reg_1111 <= and_ln149_2_fu_681_p2(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                bypassSrcOptIdx_loc_fu_146 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_bypassSrcOptIdx_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                i_50_loc_fu_134 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_i_50_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                p_loc_fu_122 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                sub173_reg_1129 <= sub173_fu_809_p3;
                sub182_reg_1134 <= sub182_fu_837_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                targetBlock15_reg_1139 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                targetBlock_reg_1036 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                tmp_71_loc_fu_114 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_tmp_71_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                    tmp_71_reload_cast_reg_1146(12 downto 0) <= tmp_71_reload_cast_fu_865_p1(12 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                tmp_73_loc_fu_110 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_tmp_73_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                xDiff_2_loc_fu_130 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                xDiff_2_phi_loc_fu_138 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_xDiff_2_phi_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                yDiff_2_loc_fu_126 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                yDiff_2_phi_loc_fu_142 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_yDiff_2_phi_out;
            end if;
        end if;
    end process;
    tmp_71_reload_cast_reg_1146(63 downto 13) <= "000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, targetBlock15_reg_1139, ap_CS_fsm_state8, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done, ap_CS_fsm_state10, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((targetBlock15_reg_1139 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                if (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    CGRA_NumTiles_shapes_values_address0 <= zext_ln233_fu_453_p1(5 - 1 downto 0);

    CGRA_NumTiles_shapes_values_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            CGRA_NumTiles_shapes_values_ce0 <= ap_const_logic_1;
        else 
            CGRA_NumTiles_shapes_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    IDX_pd_bypass_o_assign_proc : process(IDX_pd_bypass_i, ap_CS_fsm_state5, add_ln192_fu_564_p2, ap_CS_fsm_state8, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            IDX_pd_bypass_o <= add_ln192_fu_564_p2;
        elsif (((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            IDX_pd_bypass_o <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o;
        else 
            IDX_pd_bypass_o <= IDX_pd_bypass_i;
        end if; 
    end process;


    IDX_pd_bypass_o_ap_vld_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state8, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            IDX_pd_bypass_o_ap_vld <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            IDX_pd_bypass_o_ap_vld <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_IDX_pd_bypass_o_ap_vld;
        else 
            IDX_pd_bypass_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Tile2XY_0_address0 <= idxprom24_fu_443_p1(4 - 1 downto 0);
    Tile2XY_0_address1 <= idxprom20_fu_433_p1(4 - 1 downto 0);

    Tile2XY_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            Tile2XY_0_ce0 <= ap_const_logic_1;
        else 
            Tile2XY_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Tile2XY_0_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            Tile2XY_0_ce1 <= ap_const_logic_1;
        else 
            Tile2XY_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    Tile2XY_1_address0 <= idxprom24_fu_443_p1(4 - 1 downto 0);
    Tile2XY_1_address1 <= idxprom20_fu_433_p1(4 - 1 downto 0);

    Tile2XY_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            Tile2XY_1_ce0 <= ap_const_logic_1;
        else 
            Tile2XY_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Tile2XY_1_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            Tile2XY_1_ce1 <= ap_const_logic_1;
        else 
            Tile2XY_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln186_fu_552_p2 <= std_logic_vector(unsigned(bypassOptIdx_i) + unsigned(ap_const_lv8_1));
    add_ln192_fu_564_p2 <= std_logic_vector(unsigned(placement_dynamic_dict_Opt2PC_values_q0) + unsigned(ap_const_lv8_1));
    add_ln252_reload_cast_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln252_loc_fu_118),64));
    add_ln268_fu_882_p2 <= std_logic_vector(unsigned(bypassOpt_wrAddr_i) + unsigned(ap_const_lv8_1));

    allocated_tiles_shapes_values_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, zext_ln243_fu_618_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            allocated_tiles_shapes_values_address0 <= zext_ln243_fu_618_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            allocated_tiles_shapes_values_address0 <= ap_const_lv9_0;
        else 
            allocated_tiles_shapes_values_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    allocated_tiles_shapes_values_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            allocated_tiles_shapes_values_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            allocated_tiles_shapes_values_ce0 <= ap_const_logic_0;
        else 
            allocated_tiles_shapes_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    and_ln149_1_fu_675_p2 <= (xor_ln149_fu_651_p2 and and_ln153_fu_669_p2);
    and_ln149_2_fu_681_p2 <= (yDiff_210_reg_335 and xDiff_28_reg_344);
    and_ln149_3_fu_695_p2 <= (tmp_36_fu_631_p3 and and_ln153_fu_669_p2);
    and_ln149_4_fu_707_p2 <= (tmp_36_fu_631_p3 and icmp_ln153_1_fu_701_p2);
    and_ln149_fu_657_p2 <= (xor_ln149_fu_651_p2 and tmp_fu_623_p3);
    and_ln153_fu_669_p2 <= (xor_ln148_fu_663_p2 and icmp_ln153_fu_645_p2);
    and_ln205_fu_495_p2 <= (sel_tmp1_fu_489_p2 and icmp_ln205_fu_483_p2);
    and_ln218_fu_508_p2 <= (sel_tmp9_fu_502_p2 and icmp_ln218_fu_477_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done)
    begin
        if ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done)
    begin
        if ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state3_on_subcall_done_assign_proc : process(grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_done, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_done = ap_const_logic_0) or (grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_357_p4_assign_proc : process(targetBlock15_reg_1139, retval_0_reg_353, ap_CS_fsm_state11)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_phi_mux_retval_0_phi_fu_357_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_retval_0_phi_fu_357_p4 <= retval_0_reg_353;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_retval_0_phi_fu_357_p4, ap_CS_fsm_state11, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_return <= ap_phi_mux_retval_0_phi_fu_357_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    ap_sig_allocacmp_idx_pd_load_assign_proc : process(idx_pd_i, targetBlock_reg_1036, ap_CS_fsm_state5, i_50_loc_fu_134)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (targetBlock_reg_1036 = ap_const_lv1_0))) then 
            ap_sig_allocacmp_idx_pd_load <= i_50_loc_fu_134;
        else 
            ap_sig_allocacmp_idx_pd_load <= idx_pd_i;
        end if; 
    end process;

    bypassOpt <= bypassOptIdx_i;

    bypassOptIdx_o_assign_proc : process(bypassOptIdx_i, ap_CS_fsm_state5, add_ln186_fu_552_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bypassOptIdx_o <= add_ln186_fu_552_p2;
        else 
            bypassOptIdx_o <= bypassOptIdx_i;
        end if; 
    end process;


    bypassOptIdx_o_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bypassOptIdx_o_ap_vld <= ap_const_logic_1;
        else 
            bypassOptIdx_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    bypassOpt_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bypassOpt_ap_vld <= ap_const_logic_1;
        else 
            bypassOpt_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    bypassOpt_wrAddr_o_assign_proc : process(bypassOpt_wrAddr_i, targetBlock15_reg_1139, ap_CS_fsm_state9, add_ln268_fu_882_p2)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            bypassOpt_wrAddr_o <= add_ln268_fu_882_p2;
        else 
            bypassOpt_wrAddr_o <= bypassOpt_wrAddr_i;
        end if; 
    end process;


    bypassOpt_wrAddr_o_ap_vld_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            bypassOpt_wrAddr_o_ap_vld <= ap_const_logic_1;
        else 
            bypassOpt_wrAddr_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cmp28_fu_463_p2 <= "1" when (unsigned(Tile2XY_0_q1) < unsigned(Tile2XY_0_q0)) else "0";
    cmp77_fu_470_p2 <= "1" when (unsigned(Tile2XY_1_q1) < unsigned(Tile2XY_1_q0)) else "0";
    dirInIdx_fu_719_p3 <= 
        ap_const_lv3_5 when (icmp_ln169_reg_1089(0) = '1') else 
        ap_const_lv3_3;
    empty_fu_713_p2 <= (and_ln149_4_fu_707_p2 or and_ln149_3_fu_695_p2);
    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_ap_start_reg;
    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_199_2_VITIS_LOOP_233_3_fu_373_ap_start_reg;
    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_ap_start_reg;
    grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_start_reg;
    icmp_ln153_1_fu_701_p2 <= "1" when (xDiff_28_reg_344 = ap_const_lv2_0) else "0";
    icmp_ln153_fu_645_p2 <= "1" when (xDiff_28_reg_344 = ap_const_lv2_1) else "0";
    icmp_ln169_fu_639_p2 <= "1" when (yDiff_210_reg_335 = ap_const_lv2_1) else "0";
    icmp_ln205_fu_483_p2 <= "1" when (Tile2XY_0_q1 = Tile2XY_0_q0) else "0";
    icmp_ln218_fu_477_p2 <= "1" when (Tile2XY_1_q1 = Tile2XY_1_q0) else "0";

    idx_pd_o_assign_proc : process(idx_pd_i, targetBlock_reg_1036, ap_CS_fsm_state5, i_50_loc_fu_134)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (targetBlock_reg_1036 = ap_const_lv1_0))) then 
            idx_pd_o <= i_50_loc_fu_134;
        else 
            idx_pd_o <= idx_pd_i;
        end if; 
    end process;


    idx_pd_o_ap_vld_assign_proc : process(targetBlock_reg_1036, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (targetBlock_reg_1036 = ap_const_lv1_0))) then 
            idx_pd_o_ap_vld <= ap_const_logic_1;
        else 
            idx_pd_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    idxprom20_fu_433_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bypassSrcTile),64));
    idxprom24_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bypassTgtTile),64));
    p_shl_fu_519_p3 <= (CGRA_NumTiles_shapes_values_q0 & ap_const_lv2_0);
    placement_done_values_address0 <= zext_ln262_fu_873_p1(7 - 1 downto 0);

    placement_done_values_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_done_values_ce0 <= ap_const_logic_1;
        else 
            placement_done_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_done_values_d0 <= ap_const_lv1_1;

    placement_done_values_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            placement_done_values_we0 <= ap_const_logic_1;
        else 
            placement_done_values_we0 <= ap_const_logic_0;
        end if; 
    end process;


    placement_dynamic_bypass_address0_assign_proc : process(grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_address0, ap_CS_fsm_state11, ap_CS_fsm_state10, tmp_73_reload_cast_fu_897_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            placement_dynamic_bypass_address0 <= tmp_73_reload_cast_fu_897_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            placement_dynamic_bypass_address0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_address0;
        else 
            placement_dynamic_bypass_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    placement_dynamic_bypass_ce0_assign_proc : process(grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_ce0, ap_CS_fsm_state11, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            placement_dynamic_bypass_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            placement_dynamic_bypass_ce0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_placement_dynamic_bypass_ce0;
        else 
            placement_dynamic_bypass_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_bypass_d0 <= bypassOptIdx_load_reg_1045;

    placement_dynamic_bypass_occupy_address0_assign_proc : process(ap_CS_fsm_state8, tmp_71_reload_cast_reg_1146, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address0, ap_CS_fsm_state10, add_ln252_reload_cast_fu_857_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            placement_dynamic_bypass_occupy_address0 <= tmp_71_reload_cast_reg_1146(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_bypass_occupy_address0 <= add_ln252_reload_cast_fu_857_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            placement_dynamic_bypass_occupy_address0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address0;
        else 
            placement_dynamic_bypass_occupy_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    placement_dynamic_bypass_occupy_address1 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_address1;

    placement_dynamic_bypass_occupy_ce0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce0, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            placement_dynamic_bypass_occupy_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            placement_dynamic_bypass_occupy_ce0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce0;
        else 
            placement_dynamic_bypass_occupy_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    placement_dynamic_bypass_occupy_ce1_assign_proc : process(ap_CS_fsm_state8, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            placement_dynamic_bypass_occupy_ce1 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_249_4_fu_402_placement_dynamic_bypass_occupy_ce1;
        else 
            placement_dynamic_bypass_occupy_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_bypass_occupy_d0 <= ap_const_lv1_1;

    placement_dynamic_bypass_occupy_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done, ap_CS_fsm_state10)
    begin
        if ((((grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_255_5_fu_420_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            placement_dynamic_bypass_occupy_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_bypass_occupy_we0 <= ap_const_logic_0;
        end if; 
    end process;


    placement_dynamic_bypass_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state11)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            placement_dynamic_bypass_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_bypass_we0 <= ap_const_logic_0;
        end if; 
    end process;


    placement_dynamic_dict_Opt2PC_keys_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_address0, zext_ln262_fu_873_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_dict_Opt2PC_keys_address0 <= zext_ln262_fu_873_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            placement_dynamic_dict_Opt2PC_keys_address0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_address0;
        else 
            placement_dynamic_dict_Opt2PC_keys_address0 <= "XXXXXXX";
        end if; 
    end process;


    placement_dynamic_dict_Opt2PC_keys_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state9, grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_dict_Opt2PC_keys_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            placement_dynamic_dict_Opt2PC_keys_ce0 <= grp_BypassOptPlacement_Gen_Record_Pipeline_VITIS_LOOP_188_1_fu_365_placement_dynamic_dict_Opt2PC_keys_ce0;
        else 
            placement_dynamic_dict_Opt2PC_keys_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2PC_keys_d0 <= bypassOptIdx_load_reg_1045;

    placement_dynamic_dict_Opt2PC_keys_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            placement_dynamic_dict_Opt2PC_keys_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2PC_keys_we0 <= ap_const_logic_0;
        end if; 
    end process;


    placement_dynamic_dict_Opt2PC_values_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state9, zext_ln192_fu_537_p1, zext_ln262_fu_873_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_dict_Opt2PC_values_address0 <= zext_ln262_fu_873_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            placement_dynamic_dict_Opt2PC_values_address0 <= zext_ln192_fu_537_p1(7 - 1 downto 0);
        else 
            placement_dynamic_dict_Opt2PC_values_address0 <= "XXXXXXX";
        end if; 
    end process;


    placement_dynamic_dict_Opt2PC_values_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            placement_dynamic_dict_Opt2PC_values_ce0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2PC_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2PC_values_d0 <= p_loc_fu_122;

    placement_dynamic_dict_Opt2PC_values_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            placement_dynamic_dict_Opt2PC_values_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2PC_values_we0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2Tile_keys_address0 <= zext_ln262_fu_873_p1(7 - 1 downto 0);

    placement_dynamic_dict_Opt2Tile_keys_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_dict_Opt2Tile_keys_ce0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2Tile_keys_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2Tile_keys_d0 <= bypassOptIdx_load_reg_1045;

    placement_dynamic_dict_Opt2Tile_keys_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            placement_dynamic_dict_Opt2Tile_keys_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2Tile_keys_we0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2Tile_values_address0 <= zext_ln262_fu_873_p1(7 - 1 downto 0);

    placement_dynamic_dict_Opt2Tile_values_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            placement_dynamic_dict_Opt2Tile_values_ce0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2Tile_values_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    placement_dynamic_dict_Opt2Tile_values_d0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tileId_reg_1082),5));

    placement_dynamic_dict_Opt2Tile_values_we0_assign_proc : process(targetBlock15_reg_1139, ap_CS_fsm_state9)
    begin
        if (((targetBlock15_reg_1139 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            placement_dynamic_dict_Opt2Tile_values_we0 <= ap_const_logic_1;
        else 
            placement_dynamic_dict_Opt2Tile_values_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sel_tmp1_fu_489_p2 <= (cmp28_fu_463_p2 xor ap_const_lv1_1);
    sel_tmp25_cast_op_fu_796_p2 <= std_logic_vector(unsigned(zext_ln149_fu_778_p1) + unsigned(ap_const_lv4_F));
    sel_tmp29_op_cast_cast_fu_802_p3 <= 
        ap_const_lv4_1 when (and_ln149_4_reg_1117(0) = '1') else 
        ap_const_lv4_7;
    sel_tmp42_op_fu_817_p2 <= std_logic_vector(unsigned(select_ln149_5_fu_789_p3) + unsigned(ap_const_lv4_7));
    sel_tmp44_op_fu_823_p3 <= 
        ap_const_lv4_E when (tmp_37_reg_1111(0) = '1') else 
        sel_tmp42_op_fu_817_p2;
    sel_tmp48_op_fu_830_p3 <= 
        ap_const_lv4_8 when (and_ln149_4_reg_1117(0) = '1') else 
        ap_const_lv4_C;
    sel_tmp9_fu_502_p2 <= (cmp77_fu_470_p2 xor ap_const_lv1_1);
    select_ln149_1_fu_757_p3 <= 
        dirInIdx_fu_719_p3 when (and_ln149_reg_1099(0) = '1') else 
        zext_ln244_fu_747_p1;
    select_ln149_2_fu_764_p3 <= 
        select_ln155_fu_733_p3 when (and_ln149_1_reg_1105(0) = '1') else 
        select_ln149_1_fu_757_p3;
    select_ln149_3_fu_771_p3 <= 
        ap_const_lv3_6 when (tmp_37_reg_1111(0) = '1') else 
        select_ln149_2_fu_764_p3;
    select_ln149_4_fu_782_p3 <= 
        select_ln169_fu_726_p3 when (and_ln149_reg_1099(0) = '1') else 
        select_ln149_fu_750_p3;
    select_ln149_5_fu_789_p3 <= 
        select_ln244_fu_740_p3 when (and_ln149_1_reg_1105(0) = '1') else 
        select_ln149_4_fu_782_p3;
    select_ln149_fu_750_p3 <= 
        ap_const_lv4_2 when (icmp_ln169_reg_1089(0) = '1') else 
        ap_const_lv4_0;
    select_ln155_fu_733_p3 <= 
        ap_const_lv3_7 when (icmp_ln169_reg_1089(0) = '1') else 
        ap_const_lv3_4;
    select_ln169_fu_726_p3 <= 
        ap_const_lv4_8 when (icmp_ln169_reg_1089(0) = '1') else 
        ap_const_lv4_4;
    select_ln244_fu_740_p3 <= 
        ap_const_lv4_6 when (icmp_ln169_reg_1089(0) = '1') else 
        ap_const_lv4_3;
    sub173_fu_809_p3 <= 
        sel_tmp29_op_cast_cast_fu_802_p3 when (empty_reg_1123(0) = '1') else 
        sel_tmp25_cast_op_fu_796_p2;
    sub182_fu_837_p3 <= 
        sel_tmp48_op_fu_830_p3 when (empty_reg_1123(0) = '1') else 
        sel_tmp44_op_fu_823_p3;
    sub_ln192_fu_527_p2 <= std_logic_vector(unsigned(p_shl_fu_519_p3) - unsigned(zext_ln192_1_fu_515_p1));
    tmp_36_fu_631_p3 <= yDiff_210_reg_335(1 downto 1);
    tmp_71_reload_cast_fu_865_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_71_loc_fu_114),64));
    tmp_73_reload_cast_fu_897_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_73_loc_fu_110),64));
    tmp_fu_623_p3 <= xDiff_28_reg_344(1 downto 1);
    tmp_s_fu_611_p3 <= (shape_idx & ap_sig_allocacmp_idx_pd_load);
    upperLimit_fu_580_p2 <= std_logic_vector(unsigned(DynamicPlacement_II) + unsigned(add_ln192_fu_564_p2));
    xor_ln148_fu_663_p2 <= (tmp_fu_623_p3 xor ap_const_lv1_1);
    xor_ln149_fu_651_p2 <= (tmp_36_fu_631_p3 xor ap_const_lv1_1);
    zext_ln149_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln149_3_fu_771_p3),4));
    zext_ln192_1_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(CGRA_NumTiles_shapes_values_q0),6));
    zext_ln192_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bypassSrcOptIdx_loc_fu_146),64));
    zext_ln233_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shape_idx),64));
    zext_ln243_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_611_p3),64));
    zext_ln244_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln169_reg_1089),3));
    zext_ln262_fu_873_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bypassOpt_wrAddr_i),64));
end behav;
