set_property SRC_FILE_INFO {cfile:D:/Project/Vivado2021-Project/LevelMatch/LevelMatch.srcs/constrs_1/new/levelMatch.xdc rfile:../../../LevelMatch.srcs/constrs_1/new/levelMatch.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports CLK]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F5 [get_ports VALID]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports RST_n]
